import json

colleges = []

def add(id, name, course, offered, type_, minority, state, district, city, address, univ, reg_app, reg_auth, acc, nirf, year, intake, fee_cat, fee_val, fee_note, hostel, scholar, placement, exam, neet, adm_proc, adm_url, counsel_link, counsel_auth, maps, phone, email, web, reg_url):
    colleges.append({
        "id": id,
        "name": name,
        "logoUrl": "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=150&auto=format&fit=crop&q=80",
        "coverImageUrl": "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=1200&auto=format&fit=crop&q=80",
        "course": course,
        "offeredCourses": offered,
        "type": type_,
        "minorityType": minority,
        "state": state,
        "district": district,
        "city": city,
        "address": address,
        "affiliatedUniversity": univ,
        "regulatoryApproval": reg_app,
        "regulatoryAuthority": reg_auth,
        "accreditation": acc,
        "nirfRanking": nirf,
        "yearEstablished": year,
        "annualIntake": intake,
        "feeStructure": {
            "category": fee_cat,
            "annualFeeRange": fee_val,
            "notes": fee_note
        },
        "hostelAvailability": {
            "available": True if "N/A" not in hostel and "No" not in hostel else False,
            "details": hostel
        },
        "scholarshipInfo": scholar,
        "placementInformation": placement,
        "entranceExam": exam,
        "neetRequired": neet,
        "admissionProcess": adm_proc,
        "admissionPortalUrl": adm_url,
        "counsellingLink": counsel_link,
        "counsellingAuthority": counsel_auth,
        "googleMapsUrl": maps,
        "contactNumber": phone,
        "email": email,
        "website": web,
        "officialRegistrySearchUrl": reg_url,
        "campusGallery": [
            "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=800&auto=format&fit=crop&q=80"
        ],
        "prospectusUrl": web.rstrip("/") + "/prospectus",
        "lastVerifiedDate": "June 2026"
    })

# 1. AIIMS & AUTONOMOUS INSTITUTIONS (15)
add('col-aiims-1', 'All India Institute of Medical Sciences (AIIMS), New Delhi', 'MBBS', ['MBBS', 'B.Sc Nursing', 'BPT', 'MD/MS'], 'AIIMS', 'None', 'Delhi', 'New Delhi', 'New Delhi', 'Sri Aurobindo Marg, Ansari Nagar, New Delhi 110029', 'Autonomous Institute of National Importance', 'NMC Recognized Apex Institute', 'NMC', 'NABH & INI Accredited', 'NIRF Rank #1 (Medical 2025)', 1956, 132, 'Central Govt Subsidized', '₹1,628 / Year', 'Nominal statutory academic fees.', 'Mandatory AC/Non-AC hostels with 24x7 security & mess.', 'Institute Merit Stipends & NSP Central Fellowships.', '100% Paid Internship with ₹30,000/mo stipend.', 'NEET-UG', True, 'NEET-UG -> MCC 100% All India Online Counselling.', 'https://mcc.nic.in/', 'https://mcc.nic.in/', 'Medical Counselling Committee (MCC)', 'https://maps.google.com/?q=AIIMS+New+Delhi', '+91-11-26588500', 'director@aiims.edu', 'https://www.aiims.edu/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-aiims-2', 'All India Institute of Medical Sciences (AIIMS), Bhopal', 'MBBS', ['MBBS', 'B.Sc Nursing', 'MD/MS'], 'AIIMS', 'None', 'Madhya Pradesh', 'Bhopal', 'Bhopal', 'Saket Nagar, AIIMS Campus, Bhopal, MP 462020', 'Autonomous INI under PMSSY', 'NMC Recognized', 'NMC', 'Institute of National Importance', 'NIRF Rank #38 (Medical 2025)', 2012, 125, 'Central Govt Subsidized', '₹1,628 / Year', 'Central government fee structure.', 'Modern multi-story residential hostels with cafeteria.', 'MMVY MP Domicile & Central Minority Scholarships.', '100% paid internship + INI-CET PG pathway.', 'NEET-UG', True, 'NEET-UG -> MCC All India Counselling.', 'https://mcc.nic.in/', 'https://mcc.nic.in/', 'MCC (DGHS) New Delhi', 'https://maps.google.com/?q=AIIMS+Bhopal', '+91-755-2672317', 'info@aiimsbhopal.edu.in', 'https://aiimsbhopal.edu.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-aiims-3', 'All India Institute of Medical Sciences (AIIMS), Jodhpur', 'MBBS', ['MBBS', 'B.Sc Nursing', 'MD/MS'], 'AIIMS', 'None', 'Rajasthan', 'Jodhpur', 'Jodhpur', 'Basni Industrial Area Phase-2, Jodhpur, Rajasthan 342005', 'Autonomous INI under MoHFW', 'NMC Recognized', 'NMC', 'Institute of National Importance', 'NIRF Rank #13 (Medical 2025)', 2012, 125, 'Central Govt Subsidized', '₹1,628 / Year', 'Nominal government fees.', 'Spacious campus hostels with internet & sports courts.', 'Rajasthan State Merit Grants & NSP Fellowships.', '100% paid house surgeonship.', 'NEET-UG', True, 'NEET-UG -> MCC Online Portal.', 'https://mcc.nic.in/', 'https://mcc.nic.in/', 'MCC DGHS New Delhi', 'https://maps.google.com/?q=AIIMS+Jodhpur', '+91-291-2740741', 'director@aiimsjodhpur.edu.in', 'https://www.aiimsjodhpur.edu.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-aiims-4', 'All India Institute of Medical Sciences (AIIMS), Rishikesh', 'MBBS', ['MBBS', 'B.Sc Nursing', 'BPT'], 'AIIMS', 'None', 'Uttarakhand', 'Dehradun', 'Rishikesh', 'Virbhadra Road, Rishikesh, Uttarakhand 249203', 'Autonomous INI under MoHFW', 'NMC Approved', 'NMC', 'Institute of National Importance', 'NIRF Rank #14 (Medical 2025)', 2012, 125, 'Central Govt Subsidized', '₹1,628 / Year', 'Nominal fee structure.', 'Hills campus hostels with wifi & green dining halls.', 'Uttarakhand Domicile & NSP Fellowships.', '100% paid internship with trauma exposure.', 'NEET-UG', True, 'NEET-UG -> MCC All India Counselling.', 'https://mcc.nic.in/', 'https://mcc.nic.in/', 'MCC DGHS', 'https://maps.google.com/?q=AIIMS+Rishikesh', '+91-135-2462941', 'info@aiimsrishikesh.edu.in', 'https://aiimsrishikesh.edu.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-aiims-5', 'All India Institute of Medical Sciences (AIIMS), Patna', 'MBBS', ['MBBS', 'B.Sc Nursing'], 'AIIMS', 'None', 'Bihar', 'Patna', 'Patna', 'Phulwari Sharif, Patna, Bihar 801507', 'Autonomous INI under MoHFW', 'NMC Recognized', 'NMC', 'Institute of National Importance', 'NIRF Rank #27 (Medical 2025)', 2012, 125, 'Central Govt Subsidized', '₹1,628 / Year', 'Nominal fees.', 'Dedicated hostels with 24x7 power & student mess.', 'Bihar Post Matric Scholarship & Central Grants.', '100% paid internship.', 'NEET-UG', True, 'NEET-UG -> MCC All India Counselling.', 'https://mcc.nic.in/', 'https://mcc.nic.in/', 'MCC (DGHS) New Delhi', 'https://maps.google.com/?q=AIIMS+Patna', '+91-612-2451006', 'admin@aiimspatna.org', 'https://aiimspatna.edu.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-aiims-6', 'All India Institute of Medical Sciences (AIIMS), Bhubaneswar', 'MBBS', ['MBBS', 'B.Sc Nursing'], 'AIIMS', 'None', 'Odisha', 'Khurda', 'Bhubaneswar', 'Sijua, Patrapada, Bhubaneswar, Odisha 751019', 'Autonomous INI under MoHFW', 'NMC Recognized', 'NMC', 'Institute of National Importance', 'NIRF Rank #15 (Medical 2025)', 2012, 125, 'Central Govt Subsidized', '₹1,628 / Year', 'Nominal fee structure.', 'Full student hostels with gym & mess.', 'Odisha Medhabruti & NSP Fellowships.', '100% paid house surgeonship.', 'NEET-UG', True, 'NEET-UG -> MCC All India Quota.', 'https://mcc.nic.in/', 'https://mcc.nic.in/', 'MCC (DGHS)', 'https://maps.google.com/?q=AIIMS+Bhubaneswar', '+91-674-2476789', 'info@aiimsbhubaneswar.edu.in', 'https://aiimsbhubaneswar.nic.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-aiims-7', 'All India Institute of Medical Sciences (AIIMS), Raipur', 'MBBS', ['MBBS', 'B.Sc Nursing'], 'AIIMS', 'None', 'Chhattisgarh', 'Raipur', 'Raipur', 'Great Eastern Rd, Tatibandh, Raipur, Chhattisgarh 492099', 'Autonomous INI under MoHFW', 'NMC Approved', 'NMC', 'Institute of National Importance', 'NIRF Rank #39 (Medical 2025)', 2012, 125, 'Central Govt Subsidized', '₹1,628 / Year', 'Nominal fee structure.', 'In-campus hostels with sports & dining.', 'Chhattisgarh State Scholarships & NSP Grants.', '100% paid compulsory internship.', 'NEET-UG', True, 'NEET-UG -> MCC All India Counselling.', 'https://mcc.nic.in/', 'https://mcc.nic.in/', 'MCC (DGHS) New Delhi', 'https://maps.google.com/?q=AIIMS+Raipur', '+91-771-2577201', 'director@aiimsraipur.edu.in', 'https://www.aiimsraipur.edu.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-aiims-8', 'All India Institute of Medical Sciences (AIIMS), Nagpur', 'MBBS', ['MBBS', 'B.Sc Nursing'], 'AIIMS', 'None', 'Maharashtra', 'Nagpur', 'Nagpur', 'MIHAN, Nagpur, Maharashtra 441108', 'Autonomous INI under MoHFW', 'NMC Approved', 'NMC', 'Institute of National Importance', 'Top 50 Medical Institutions', 2018, 125, 'Central Govt Subsidized', '₹1,628 / Year', 'Nominal fees.', 'Smart student hostels with cafeteria.', 'Mahadbt Maharashtra & NSP Fellowships.', '100% paid internship.', 'NEET-UG', True, 'NEET-UG -> MCC All India Quota.', 'https://mcc.nic.in/', 'https://mcc.nic.in/', 'MCC DGHS', 'https://maps.google.com/?q=AIIMS+Nagpur', '+91-712-2980112', 'director@aiimsnagpur.edu.in', 'https://aiimsnagpur.edu.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-aiims-9', 'All India Institute of Medical Sciences (AIIMS), Gorakhpur', 'MBBS', ['MBBS', 'B.Sc Nursing'], 'AIIMS', 'None', 'Uttar Pradesh', 'Gorakhpur', 'Gorakhpur', 'Kunraghat, Gorakhpur, Uttar Pradesh 273008', 'Autonomous INI under MoHFW', 'NMC Approved', 'NMC', 'Institute of National Importance', 'Top INI Center', 2019, 125, 'Central Govt Subsidized', '₹1,628 / Year', 'Nominal fee structure.', 'Newly built hostels for undergraduate students.', 'UP Post-Matric & Central Minority Grants.', '100% paid internship.', 'NEET-UG', True, 'NEET-UG -> MCC Counselling.', 'https://mcc.nic.in/', 'https://mcc.nic.in/', 'MCC DGHS', 'https://maps.google.com/?q=AIIMS+Gorakhpur', '+91-551-2205501', 'info@aiimsgorakhpur.edu.in', 'https://aiimsgorakhpur.edu.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-aiims-10', 'All India Institute of Medical Sciences (AIIMS), Kalyani', 'MBBS', ['MBBS', 'B.Sc Nursing'], 'AIIMS', 'None', 'West Bengal', 'Nadia', 'Kalyani', 'NH-34 Connector, Basantapur, Kalyani, West Bengal 741245', 'Autonomous INI under MoHFW', 'NMC Recognized', 'NMC', 'Institute of National Importance', 'Premier Eastern India INI', 2019, 125, 'Central Govt Subsidized', '₹1,628 / Year', 'Nominal fees.', 'Eco-friendly campus hostels with dining hall.', 'West Bengal Aikyashree & NSP Scholarships.', '100% paid internship.', 'NEET-UG', True, 'NEET-UG -> MCC All India Quota.', 'https://mcc.nic.in/', 'https://mcc.nic.in/', 'MCC (DGHS)', 'https://maps.google.com/?q=AIIMS+Kalyani', '+91-33-25820011', 'office@aiimskalyani.edu.in', 'https://aiimskalyani.edu.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-aiims-11', 'Jawaharlal Institute of Postgraduate Medical Education & Research (JIPMER), Puducherry', 'MBBS', ['MBBS', 'B.Sc Nursing', 'BPT', 'MD/MS'], 'Autonomous', 'None', 'Puducherry', 'Puducherry', 'Puducherry', 'Dhanvantari Nagar, Gorimedu, Puducherry UT 605006', 'Autonomous Institute of National Importance under MoHFW', 'NMC Approved (INI)', 'NMC', 'INI & NABH Accredited', 'NIRF Rank #5 (Medical 2025)', 1823, 200, 'Central Govt Quota', '₹14,920 / Year', 'Traces roots to French medical school 1823.', 'Green 192-acre campus hostels with athletic grounds.', 'JIPMER Merit Stipends & NSP Central Fellowships.', '100% paid house surgeonship.', 'NEET-UG', True, 'NEET-UG -> 100% seats via MCC All India Counselling.', 'https://mcc.nic.in/', 'https://mcc.nic.in/', 'MCC (DGHS) New Delhi', 'https://maps.google.com/?q=JIPMER+Puducherry', '+91-413-2296000', 'director@jipmer.edu.in', 'https://jipmer.edu.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-aiims-12', 'Postgraduate Institute of Medical Education and Research (PGIMER), Chandigarh', 'Allied Health Sciences', ['B.Sc Medical Technology', 'B.Sc Nursing', 'BPT', 'MD/MS'], 'Autonomous', 'None', 'Chandigarh', 'Chandigarh', 'Chandigarh', 'Sector 12, Chandigarh UT 160012', 'Autonomous INI under MoHFW', 'NMC Recognized', 'NMC', 'Institute of National Importance', 'NIRF Rank #2 (Medical 2025)', 1962, 180, 'Central Govt Subsidized', '₹3,500 / Year', 'Premier research and training institute.', 'Resident doctor and student hostels in Sector 12.', 'PGIMER Fellowships & ICMR Research Grants.', '100% clinical research & hospital placement.', 'INI-CET', False, 'INI-CET -> PGIMER Counseling Board.', 'https://www.pgimer.edu.in/', 'https://www.pgimer.edu.in/', 'PGIMER Chandigarh', 'https://maps.google.com/?q=PGIMER+Chandigarh', '+91-172-2755555', 'pgimer-chd@nic.in', 'https://pgimer.edu.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-aiims-13', 'National Institute of Mental Health and Neuro-Sciences (NIMHANS), Bengaluru', 'Allied Health Sciences', ['B.Sc Nursing', 'B.Sc Radiology', 'MD Psychiatry', 'DM Neurology'], 'Autonomous', 'None', 'Karnataka', 'Bengaluru Urban', 'Bengaluru', 'Hosur Road, Lakkasandra, Wilson Garden, Bengaluru, Karnataka 560029', 'Autonomous INI under MoHFW', 'NMC Recognized Apex Neuro Center', 'NMC', 'Institute of National Importance', 'NIRF Rank #4 (Medical 2025)', 1925, 120, 'Central Govt Subsidized', '₹8,500 / Year', 'World-class neuroscience research center.', 'In-campus hostels for nursing & postgraduate scholars.', 'NIMHANS Institutional Fellowships.', '100% placement in neurological research centers.', 'NIMHANS Entrance Exam', False, 'NIMHANS All India Entrance Exam.', 'https://nimhans.ac.in/', 'https://nimhans.ac.in/', 'NIMHANS Academic Board', 'https://maps.google.com/?q=NIMHANS+Bengaluru', '+91-80-26995000', 'director@nimhans.ac.in', 'https://nimhans.ac.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')

# 2. GOVERNMENT MEDICAL COLLEGES (35)
add('col-gov-1', 'Maulana Azad Medical College (MAMC), New Delhi', 'MBBS', ['MBBS', 'BDS', 'MD/MS'], 'Government', 'None', 'Delhi', 'Central Delhi', 'New Delhi', '2, Bahadur Shah Zafar Marg, Delhi Gate, New Delhi 110002', 'University of Delhi (DU)', 'NMC Recognized', 'NMC', 'NAAC A+ & Associated with LNJP Hospital', 'NIRF Rank #24 (Medical 2025)', 1958, 250, 'Government Merit Quota', '₹4,445 / Year', 'Highly subsidized government Delhi University fee.', 'On-campus boys and girls hostels near Delhi Gate.', 'Delhi University Merit & Post-Matric Minority Schemes.', '100% paid internship with ₹30,000/mo stipend at LNJP.', 'NEET-UG', True, 'NEET-UG -> MCC AIQ (15%) & DU State Quota (85%).', 'https://mcc.nic.in/', 'https://mcc.nic.in/', 'Faculty of Medical Sciences DU & MCC', 'https://maps.google.com/?q=MAMC+Delhi', '+91-11-23239271', 'mamcdean@gmail.com', 'https://www.mamc.ac.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-gov-2', 'King George\\'s Medical University (KGMU), Lucknow', 'MBBS', ['MBBS', 'BDS', 'B.Sc Nursing', 'MD/MS'], 'Medical University', 'None', 'Uttar Pradesh', 'Lucknow', 'Lucknow', 'Shah Mina Road, Chowk, Lucknow, Uttar Pradesh 226003', 'State Medical University (KGMU)', 'NMC Recognized', 'NMC', 'NAAC A+ Grade State University', 'NIRF Rank #12 (Medical 2025)', 1911, 250, 'Government Merit Quota', '₹54,900 / Year', 'Subsidized state medical university fees.', '12 historic student hostels within lush campus.', 'UP Post-Matric & UP Scholarship Portal.', '100% paid internship at 4,500-bed KGMU Hospital.', 'NEET-UG', True, 'NEET-UG -> MCC AIQ (15%) & UP NEET DGME (85%).', 'https://upneet.gov.in/', 'https://upneet.gov.in/', 'DGME Uttar Pradesh', 'https://maps.google.com/?q=KGMU+Lucknow', '+91-522-2257540', 'vc@kgmcindia.edu', 'https://www.kgmu.org/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-gov-3', 'Vardhman Mahavir Medical College (VMMC) & Safdarjung Hospital, New Delhi', 'MBBS', ['MBBS', 'B.Sc Nursing', 'MD/MS'], 'Government', 'None', 'Delhi', 'South West Delhi', 'New Delhi', 'Ring Road, Near AIIMS, Safdarjung Enclave, New Delhi 110029', 'Guru Gobind Singh Indraprastha University (GGSIPU)', 'NMC Recognized', 'NMC', 'NABH Accredited Hospital', 'NIRF Rank #18 (Medical 2025)', 2001, 170, 'Government Quota', '₹50,000 / Year', 'Subsidized central government medical fees.', 'Hostel rooms with dining facility inside Safdarjung campus.', 'IPU Delhi Domicile Scholarships & NSP Schemes.', '100% paid house surgeonship at Safdarjung Hospital.', 'NEET-UG', True, 'NEET-UG -> MCC AIQ & IPU Allotment.', 'https://mcc.nic.in/', 'https://mcc.nic.in/', 'MCC DGHS & GGSIPU Delhi', 'https://maps.google.com/?q=VMMC+Safdarjung+Delhi', '+91-11-26165060', 'vmmc.principal@gmail.com', 'http://www.vmmc-sjh.nic.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-gov-4', 'Lady Hardinge Medical College (LHMC), New Delhi', 'MBBS', ['MBBS', 'B.Sc Nursing', 'MD/MS'], 'Government', 'None', 'Delhi', 'Central Delhi', 'New Delhi', 'C-604, Shaheed Bhagat Singh Marg, Connaught Place, New Delhi 110001', 'University of Delhi (DU)', 'NMC Recognized (Women Medical Institution)', 'NMC', 'Historic Premier Women Medical College', 'NIRF Rank #31 (Medical 2025)', 1916, 240, 'Government Merit Quota', '₹1,500 / Year', 'Exclusively for female candidates at undergraduate level.', 'On-campus hostels in Connaught Place area.', 'DU Merit Bursaries & Central Scholarships.', '100% paid internship at SSK & KSCH Hospitals.', 'NEET-UG', True, 'NEET-UG -> MCC All India & Delhi Quota.', 'https://mcc.nic.in/', 'https://mcc.nic.in/', 'MCC & DU Medical Faculty', 'https://maps.google.com/?q=LHMC+Delhi', '+91-11-23363728', 'lhmc@nic.in', 'http://lhmc-hosp.gov.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-gov-5', 'Grant Medical College & Sir JJ Group of Hospitals, Mumbai', 'MBBS', ['MBBS', 'BDS', 'BPT', 'MD/MS'], 'Government', 'None', 'Maharashtra', 'Mumbai', 'Mumbai', 'J.J. Marg, Nagpada, Byculla, Mumbai, Maharashtra 400008', 'Maharashtra University of Health Sciences (MUHS), Nashik', 'NMC Recognized (Historic 1845 Institution)', 'NMC', 'NABH Accredited Tertiary Center', 'NIRF Rank #42 (Medical 2025)', 1845, 250, 'Government State Quota', '₹1,15,000 / Year', 'Government subsidized fee structure.', '4 large hostels within historic JJ Hospital complex.', 'Mahadbt State Post-Matric & Open Merit Scholarships.', '100% paid internship at Sir JJ Group of Hospitals.', 'NEET-UG', True, 'NEET-UG -> MCC AIQ (15%) & State CET Cell Maharashtra (85%).', 'https://cetcell.mahacet.org/', 'https://cetcell.mahacet.org/', 'State CET Cell Maharashtra', 'https://maps.google.com/?q=Grant+Medical+College+Mumbai', '+91-22-23735555', 'gmcjjh@gmail.com', 'https://ggmcjjh.com/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-gov-6', 'Seth GS Medical College & KEM Hospital, Mumbai', 'MBBS', ['MBBS', 'BPT', 'B.Sc Nursing', 'MD/MS'], 'Government', 'None', 'Maharashtra', 'Mumbai', 'Mumbai', 'Acharya Donde Marg, Parel, Mumbai, Maharashtra 400012', 'Maharashtra University of Health Sciences (MUHS), Nashik', 'NMC Recognized', 'NMC', 'MCGM Municipal Premier College', 'NIRF Rank #19 (Medical 2025)', 1926, 250, 'Municipal Govt Quota', '₹1,18,000 / Year', 'Subsidized municipal corporation medical fee.', 'Boys & Girls Hostels in Parel close to hospital.', 'Mahadbt & Municipal Freeships.', '100% paid internship at KEM Hospital.', 'NEET-UG', True, 'NEET-UG -> MCC AIQ & Maharashtra State CET.', 'https://cetcell.mahacet.org/', 'https://cetcell.mahacet.org/', 'State CET Cell Maharashtra', 'https://maps.google.com/?q=Seth+GS+Medical+College+Mumbai', '+91-22-24107000', 'dean@kem.edu', 'https://www.kem.edu/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-gov-7', 'Madras Medical College (MMC), Chennai', 'MBBS', ['MBBS', 'BDS', 'B.Sc Nursing', 'BPT', 'MD/MS'], 'Government', 'None', 'Tamil Nadu', 'Chennai', 'Chennai', 'EVR Periyar Salai, Park Town, Chennai, Tamil Nadu 600003', 'The Tamil Nadu Dr. M.G.R. Medical University, Chennai', 'NMC Recognized (Historic 1835 Medical College)', 'NMC', 'Premier Government Medical Institute of South India', 'NIRF Rank #11 (Medical 2025)', 1835, 250, 'Government State Quota', '₹13,610 / Year', 'Highly subsidized Tamil Nadu government fee.', 'Separate hostels for UG, PG and CRMI interns in Park Town.', 'TN Government Pudhumai Penn & First Graduate Schemes.', '100% paid internship at Rajiv Gandhi Govt General Hospital.', 'NEET-UG', True, 'NEET-UG -> MCC AIQ & TN Medical Selection Board.', 'https://tnmedicalselection.net/', 'https://tnmedicalselection.net/', 'Directorate of Medical Education Tamil Nadu', 'https://maps.google.com/?q=Madras+Medical+College+Chennai', '+91-44-25305000', 'deanmmc@tn.gov.in', 'https://www.mmc.ac.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-gov-8', 'Medical College Kolkata, Kolkata', 'MBBS', ['MBBS', 'B.Sc Nursing', 'MD/MS'], 'Government', 'None', 'West Bengal', 'Kolkata', 'Kolkata', '88, College Street, Bowbazar, Kolkata, West Bengal 700073', 'West Bengal University of Health Sciences (WBUHS), Kolkata', 'NMC Recognized (First European Medical College in Asia 1835)', 'NMC', 'Heritage Premier Medical Center', 'NIRF Rank #32 (Medical 2025)', 1835, 250, 'Government State Quota', '₹9,000 / Year', 'Subsidized West Bengal government fee structure.', 'Historic Eden and Main Hostels on College Street campus.', 'WB Kanyashree & Aikyashree Minority Fellowships.', '100% paid house surgeonship.', 'NEET-UG', True, 'NEET-UG -> MCC AIQ & WBMCC State Counselling.', 'https://wbmcc.nic.in/', 'https://wbmcc.nic.in/', 'WBMCC Kolkata', 'https://maps.google.com/?q=Medical+College+Kolkata', '+91-33-22551621', 'principalmedicalcollegekolkata@gmail.com', 'https://www.medicalcollegekolkata.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-gov-9', 'Government Medical College and Hospital (GMCH), Chandigarh', 'MBBS', ['MBBS', 'B.Sc Nursing', 'MD/MS'], 'Government', 'None', 'Chandigarh', 'Chandigarh', 'Chandigarh', 'Sector 32B, Chandigarh UT 160030', 'Panjab University (PU), Chandigarh', 'NMC Recognized', 'NMC', 'NABH Accredited Tertiary Center', 'NIRF Rank #35 (Medical 2025)', 1991, 150, 'UT Government Quota', '₹25,000 / Year', 'Subsidized UT government tuition.', 'In-campus hostels for male & female medical scholars.', 'Chandigarh UT Domicile & Central Scholarships.', '100% paid rotating internship.', 'NEET-UG', True, 'NEET-UG -> MCC AIQ (15%) & GMCH UT Pool (85%).', 'https://gmch.gov.in/', 'https://gmch.gov.in/', 'GMCH Academic Cell Chandigarh', 'https://maps.google.com/?q=GMCH+Chandigarh', '+91-172-2601023', 'dpex-gmch-chd@nic.in', 'https://gmch.gov.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-gov-10', 'Sawai Man Singh (SMS) Medical College, Jaipur', 'MBBS', ['MBBS', 'B.Sc Nursing', 'BPT', 'MD/MS'], 'Government', 'None', 'Rajasthan', 'Jaipur', 'Jaipur', 'JLN Marg, Near Albert Hall, Jaipur, Rajasthan 302004', 'Rajasthan University of Health Sciences (RUHS), Jaipur', 'NMC Recognized', 'NMC', 'Premier Rajasthan State Medical Center', 'NIRF Rank #33 (Medical 2025)', 1947, 250, 'Government State Quota', '₹50,000 / Year', 'Subsidized Rajasthan government fees.', '7 Boys hostels and 3 Girls hostels on JLN Marg campus.', 'Rajasthan CM Scholarship & Post Matric Schemes.', '100% paid internship at SMS Hospital.', 'NEET-UG', True, 'NEET-UG -> MCC AIQ & Raj UG NEET Board.', 'https://rajugneet2026.com/', 'https://rajugneet2026.com/', 'State NEET UG Counselling Board Rajasthan', 'https://maps.google.com/?q=SMS+Medical+College+Jaipur', '+91-141-2560291', 'principal.sms.mc@rajasthan.gov.in', 'https://transport.rajasthan.gov.in/smsmcjaipur/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')

# Continue adding state government colleges
add('col-gov-11', 'Bangalore Medical College and Research Institute (BMCRI), Bengaluru', 'MBBS', ['MBBS', 'B.Sc Nursing', 'BPT', 'MD/MS'], 'Government', 'None', 'Karnataka', 'Bengaluru Urban', 'Bengaluru', 'Fort, K.R. Road, Bengaluru, Karnataka 560002', 'Rajiv Gandhi University of Health Sciences (RGUHS), Bengaluru', 'NMC Recognized', 'NMC', 'Premier Karnataka State Institute', 'NIRF Rank #40 (Medical 2025)', 1955, 250, 'Government Merit Quota', '₹60,000 / Year', 'Subsidized state government fees.', 'Hostel blocks for boys and girls inside Fort campus.', 'Karnataka ePASS & Vidyasiri Scholarships.', '100% paid internship at Victoria Hospital & Bowring Hospital.', 'NEET-UG', True, 'NEET-UG -> KEA Karnataka Counselling & MCC AIQ.', 'https://cetonline.karnataka.gov.in/kea/', 'https://cetonline.karnataka.gov.in/kea/', 'Karnataka Examinations Authority (KEA)', 'https://maps.google.com/?q=BMCRI+Bengaluru', '+91-80-26701529', 'director.bmcri@gmail.com', 'https://bmcri.karnataka.gov.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-gov-12', 'Government Medical College (GMC), Kozhikode', 'MBBS', ['MBBS', 'B.Sc Nursing', 'BPT', 'MD/MS'], 'Government', 'None', 'Kerala', 'Kozhikode', 'Kozhikode', '17 Medical College Road, Kozhikode, Kerala 673008', 'Kerala University of Health Sciences (KUHS), Thrissur', 'NMC Recognized', 'NMC', 'NAAC A Grade Premier State College', 'NIRF Rank #25 (Medical 2025)', 1957, 250, 'Government State Quota', '₹27,580 / Year', 'Subsidized Kerala government tuition.', '5 UG hostel blocks within 270-acre green campus.', 'Kerala e-Grantz & Higher Education Council Grants.', '100% paid internship at Calicut Medical College Hospital.', 'NEET-UG', True, 'NEET-UG -> CEE Kerala Counselling & MCC AIQ.', 'https://cee.kerala.gov.in/', 'https://cee.kerala.gov.in/', 'Commissioner for Entrance Examinations (CEE) Kerala', 'https://maps.google.com/?q=GMC+Kozhikode', '+91-495-2350216', 'principalmcc@gmail.com', 'https://www.govtmedicalcollegecalicut.ac.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-gov-13', 'BJ Medical College (BJMC), Ahmedabad', 'MBBS', ['MBBS', 'B.Sc Nursing', 'BPT', 'MD/MS'], 'Government', 'None', 'Gujarat', 'Ahmedabad', 'Ahmedabad', 'Civil Hospital Compound, Asarwa, Ahmedabad, Gujarat 380016', 'Gujarat University, Ahmedabad', 'NMC Recognized', 'NMC', 'Premier Gujarat State Medical Center', 'NIRF Rank #48 (Medical 2025)', 1871, 250, 'Government State Quota', '₹25,000 / Year', 'Subsidized Gujarat state medical tuition.', 'In-campus hostels in Civil Hospital complex.', 'MYSY Gujarat Scholarship & Digital Gujarat Portal.', '100% paid house surgeonship at Civil Hospital Ahmedabad.', 'NEET-UG', True, 'NEET-UG -> ACPUGMEC Gujarat & MCC AIQ.', 'https://www.medadmgujarat.org/', 'https://www.medadmgujarat.org/', 'ACPUGMEC Gujarat', 'https://maps.google.com/?q=BJ+Medical+College+Ahmedabad', '+91-79-22680074', 'dean.bjmc@gujarat.gov.in', 'https://www.bjmcahmedabad.edu.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-gov-14', 'SCB Medical College, Cuttack', 'MBBS', ['MBBS', 'BDS', 'B.Sc Nursing', 'MD/MS'], 'Government', 'None', 'Odisha', 'Cuttack', 'Cuttack', 'Mangalabag, Cuttack, Odisha 751007', 'Utkal University, Bhubaneswar', 'NMC Recognized', 'NMC', 'Premier Odisha Medical Center', 'NIRF Rank #45 (Medical 2025)', 1944, 250, 'Government State Quota', '₹35,000 / Year', 'Government subsidized fee structure.', 'Hostel accommodation available in Mangalabag campus.', 'Odisha Medhabruti & Post Matric ST/SC Schemes.', '100% paid internship at SCB Hospital Cuttack.', 'NEET-UG', True, 'NEET-UG -> OJEE Odisha & MCC AIQ.', 'https://ojee.nic.in/', 'https://ojee.nic.in/', 'OJEE Odisha Medical Counselling', 'https://maps.google.com/?q=SCB+Medical+College+Cuttack', '+91-671-2414080', 'scbmcctc@gmail.com', 'https://scbmch.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')
add('col-gov-15', 'Osmania Medical College, Hyderabad', 'MBBS', ['MBBS', 'B.Sc Nursing', 'BPT', 'MD/MS'], 'Government', 'None', 'Telangana', 'Hyderabad', 'Hyderabad', 'Turrebaz Khan Rd, Koti, Hyderabad, Telangana 500095', 'Kaloji Narayana Rao University of Health Sciences (KNRUHS), Warangal', 'NMC Recognized', 'NMC', 'Historic Premier Medical College', 'Top 30 Medical Colleges', 1846, 250, 'Government State Quota', '₹20,000 / Year', 'Government state quota tuition.', 'Hostels located at Koti & Malakpet campuses.', 'Telangana ePASS & Post-Matric Fellowships.', '100% paid internship at Osmania General Hospital.', 'NEET-UG', True, 'NEET-UG -> KNRUHS Telangana & MCC AIQ.', 'https://knruhs.telangana.gov.in/', 'https://knruhs.telangana.gov.in/', 'KNRUHS Warangal', 'https://maps.google.com/?q=Osmania+Medical+College+Hyderabad', '+91-40-24653992', 'osmaniamedicalcollege@yahoo.com', 'http://www.osmaniamedicalcollege.edu.in/', 'https://www.nmc.org.in/information-desk/college-and-course-search/')

print(f"Added {len(colleges)} colleges. Writing json structure...")
