export const matrimonialProfiles: any[] = [];
export const bloodDonors: any[] = [];
export const jobListings: any[] = [];
export const governmentSchemes: any[] = [];
export const communityEvents: any[] = [];
export const newsArticles: any[] = [];
export const mockProfessionals: any[] = [];
export const mockSuccessStories: any[] = [];
export const districtsByState: Record<string, any> = {};
