import { Proposal, CommentSuggestion, Resolution, AIAnalyticsData } from './types';

export const INITIAL_PROPOSALS_DATA: Proposal[] = [
  {
    id: 'prop-1',
    docketNo: 'PROP-2026-NAT-8841',
    titleEn: 'Establishment of National Rangrez Artisan & Handblock E-Commerce Marketplace',
    titleHi: 'राष्ट्रीय रंगरेज कारीगर एवं हैंडब्लॉक ई-कॉमर्स मार्केटप्लेस की स्थापना',
    titleUr: 'قومی رنگریز کاریگر اور ہینڈ بلاک ای کامرس مارکیٹ پلیس کا قیام',
    proposerEn: 'Haji Mohammad Rafiq Rangrez (Convener, Jaipur Textile Association)',
    proposerHi: 'हाजी मोहम्मद रफीक रंगरेज (संयोजक, जयपुर टेक्सटाइल एसोसिएशन)',
    proposerUr: 'حاجی محمد رفیق رنگریز (کنوینر، جے پور ٹیکسٹائل ایسوسی ایشن)',
    districtEn: 'Jaipur District, Rajasthan',
    districtHi: 'जिला जयपुर, राजस्थान',
    districtUr: 'ضلع جے پور، راجستھان',
    categoryEn: 'Economic & Artisan Empowerment',
    categoryHi: 'आर्थिक एवं कारीगर सशक्तिकरण',
    categoryUr: 'اقتصادی اور کاریگر کو بااختیار بنانا',
    descriptionEn: 'Creation of a dedicated zero-commission online portal and mobile app connected with ONDC and global export buyers to eliminate middlemen and empower 5,000+ traditional Rangrez dye and textile families.',
    descriptionHi: 'बिचौलियों को खत्म करने और 5,000+ पारंपरिक रंगरेज रंगाई और वस्त्र परिवारों को सशक्त बनाने के लिए ONDC और वैश्विक निर्यात खरीदारों से जुड़ा एक समर्पित शून्य-कमीशन ऑनलाइन पोर्टल और मोबाइल ऐप बनाना।',
    descriptionUr: 'بچولیوں کو ختم کرنے اور 5,000+ روایتی رنگریز رنگائی اور ٹیکسٹائل خاندانوں کو بااختیار بنانے کے لیے ONDC اور عالمی برآمدی خریداروں سے جڑا ایک مخصوص زیرو کمیشن آن لائن پورٹل اور موبائل ایپ بنانا۔',
    benefitsEn: '• 100% direct profit retention for weavers & dyers.\n• Free international shipping certification and ONDC digital catalog onboarding.\n• Financial inclusion for 3,500+ women artisans working from home.',
    benefitsHi: '• बुनकरों और रंगरेजों के लिए 100% सीधा लाभ।\n• निःशुल्क अंतर्राष्ट्रीय शिपिंग प्रमाणन और ONDC डिजिटल कैटलॉग ऑनबोर्डिंग।\n• घर से काम करने वाली 3,500+ महिला कारीगरों का वित्तीय समावेशन।',
    benefitsUr: '• بنکروں اور رنگریزوں کے لیے 100% براہ راست منافع۔\n• مفت بین الاقوامی شپنگ سرٹیفکیشن اور ONDC ڈیجیٹل کیٹلاگ آن بورڈنگ۔\n• گھر سے کام کرنے والی 3,500+ خواتین کاریگروں کی مالی شمولیت۔',
    supportingDocs: [
      { name: 'ONDC_Integration_Roadmap_2026.pdf', size: '2.4 MB', url: '#', type: 'pdf' },
      { name: 'Artisan_Cooperative_Bylaws.docx', size: '1.1 MB', url: '#', type: 'doc' }
    ],
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=600&auto=format&fit=crop&q=80'
    ],
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    upvotes: 342,
    minSupportThreshold: 200,
    commentsCount: 28,
    workflowStage: 'eligible_for_voting',
    status: 'shortlisted_for_summit',
    dateSubmitted: '18 June 2026'
  },
  {
    id: 'prop-2',
    docketNo: 'PROP-2026-UP-7102',
    titleEn: 'Mandatory Pre-Marital Counseling & Free Legal Aid Cell for Matrimonial Disputes',
    titleHi: 'अनिवार्य विवाह पूर्व परामर्श एवं वैवाहिक विवादों के लिए निःशुल्क कानूनी सहायता प्रकोष्ठ',
    titleUr: 'لازمی قبل از شادی کونسلنگ اور ازدواجی تنازعات کے لیے مفت قانونی امدادی سیل',
    proposerEn: 'Advocate Zainab Bibi Rangrez (Women Rights Wing, Lucknow)',
    proposerHi: 'एडवोकेट जैनब बीबी रंगरेज (महिला अधिकार विंग, लखनऊ)',
    proposerUr: 'ایڈووکیٹ زینب بی بی رنگریز (خواتین رائٹس ونگ، لکھنؤ)',
    districtEn: 'Lucknow District, Uttar Pradesh',
    districtHi: 'जिला लखनऊ, उत्तर प्रदेश',
    districtUr: 'ضلع لکھنؤ، اتر پردیش',
    categoryEn: 'Legal Aid & Social Harmony',
    categoryHi: 'कानूनी सहायता एवं सामाजिक सद्भाव',
    categoryUr: 'قانونی امداد اور سماجی ہم آہنگی',
    descriptionEn: 'To reduce divorce rates and family disputes, propose setting up district-level Sharia & Legal reconciliation committees that provide free mediation and compulsory 2-session pre-marital counseling for couples.',
    descriptionHi: 'तलाक की दर और पारिवारिक विवादों को कम करने के लिए, जिला स्तरीय शरिया एवं कानूनी सुलह समितियां स्थापित करने का प्रस्ताव जो निःशुल्क मध्यस्थता और जोड़ों के लिए अनिवार्य 2-सत्र विवाह पूर्व परामर्श प्रदान करेंगी।',
    descriptionUr: 'طلاق کی شرح اور خاندانی تنازعات کو کم کرنے کے لیے، ضلع کی سطح پر شریعہ اور قانونی مصالحت کمیٹیاں قائم کرنے کی تجویز جو جوڑوں کے لیے مفت ثالثی اور لازمی 2 سیشن قبل از شادی کونسلنگ فراہم کریں گی۔',
    benefitsEn: '• Drastic reduction in costly family litigation.\n• Confidential, respectful elder mediation protecting family dignity.\n• Free legal awareness sessions on women’s property and Mehar rights.',
    benefitsHi: '• महंगे पारिवारिक मुकदमों में भारी कमी।\n• परिवार की गरिमा की रक्षा करने वाली गोपनीय, सम्मानजनक बुजुर्ग मध्यस्थता।\n• महिलाओं के संपत्ति और मेहर अधिकारों पर निःशुल्क कानूनी जागरूकता।',
    benefitsUr: '• مہنگی خاندانی قانونی چارہ جوئی میں نمایاں کمی۔\n• خاندان کے وقار کی حفاظت کرنے والی خفیہ، احترام پر مبنی بزرگ ثالثی۔\n• خواتین کے جائیداد اور مہر کے حقوق پر مفت قانونی آگاہی سیشنز۔',
    supportingDocs: [
      { name: 'Sharia_Legal_Reconciliation_Charter.pdf', size: '1.8 MB', url: '#', type: 'pdf' }
    ],
    images: [
      'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80'
    ],
    videoUrl: '',
    upvotes: 185,
    minSupportThreshold: 200,
    commentsCount: 19,
    workflowStage: 'support_collection',
    status: 'under_review',
    dateSubmitted: '22 June 2026'
  },
  {
    id: 'prop-3',
    docketNo: 'PROP-2026-MP-4519',
    titleEn: 'Youth Anti-Addiction Taskforce & Sports Infrastructure Grants in Every Tehsil',
    titleHi: 'प्रत्येक तहसील में युवा नशा मुक्ति कार्यबल एवं खेल अवसंरचना अनुदान',
    titleUr: 'ہر تحصیل میں یوتھ اینٹی ایڈکشن ٹاسک فورس اور اسپورٹس انفرااسٹرکچر گرانٹس',
    proposerEn: 'Faisal Ahmad Rangrez (Youth Welfare Committee, Indore)',
    proposerHi: 'फैसल अहमद रंगरेज (युवा कल्याण समिति, इंदौर)',
    proposerUr: 'فیصل احمد رنگریز (یوتھ ویلفیئر کمیٹی، اندور)',
    districtEn: 'Indore District, Madhya Pradesh',
    districtHi: 'जिला इंदौर, मध्य प्रदेश',
    districtUr: 'ضلع اندور، مدھیہ پردیش',
    categoryEn: 'Youth Welfare & Sports',
    categoryHi: 'युवा कल्याण एवं खेल',
    categoryUr: 'یوتھ ویلفیئر اور اسپورٹس',
    descriptionEn: 'Establishment of local counseling squads, gymnasium subsidies, and annual state-level sports tournaments to protect youth from substance abuse and promote physical fitness.',
    descriptionHi: 'युवाओं को नशे से बचाने और शारीरिक फिटनेस को बढ़ावा देने के लिए स्थानीय परामर्श दस्तों, जिमनाजियम सब्सिडी और वार्षिक राज्य स्तरीय खेल टूर्नामेंटों की स्थापना।',
    descriptionUr: 'نوجوانوں کو منشیات سے بچانے اور جسمانی تندرستی کو فروغ دینے کے لیے مقامی کونسلنگ اسکواڈز، جمنازیم سبسڈی اور سالانہ ریاستی سطح کے کھیلوں کے ٹورنامنٹس کا قیام۔',
    benefitsEn: '• Direct engagement of 15,000+ youth in district sports leagues.\n• Subsidized gym and fitness memberships in rural tehsils.\n• Confidential psychological counseling and rehabilitation aid.',
    benefitsHi: '• जिला खेल लीगों में 15,000+ युवाओं की सीधी भागीदारी।\n• ग्रामीण तहसीलों में रियायती जिम और फिटनेस सदस्यता।\n• गोपनीय मनोवैज्ञानिक परामर्श और पुनर्वास सहायता।',
    benefitsUr: '• ڈسٹرکٹ اسپورٹس لیگز میں 15,000+ نوجوانوں کی شمولیت۔\n• دیہی تحصیلوں میں رعایتی جم اور فٹنس ممبرشپ۔\n• خفیہ نفسیاتی کونسلنگ اور بحالی امداد۔',
    supportingDocs: [
      { name: 'Tehsil_Sports_Grant_Budget_2026.pdf', size: '3.1 MB', url: '#', type: 'pdf' }
    ],
    images: [
      'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=600&auto=format&fit=crop&q=80'
    ],
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    upvotes: 512,
    minSupportThreshold: 200,
    commentsCount: 44,
    workflowStage: 'mahapanchayat_discussion',
    status: 'approved_for_ballot',
    dateSubmitted: '25 June 2026'
  }
];

export const INITIAL_COMMENTS_DATA: CommentSuggestion[] = [
  {
    id: 'comm-1',
    surveyOrProposalId: 'surv-1',
    authorName: 'Tariq Anwar Rangrez',
    authorDistrict: 'Ajmer, Rajasthan',
    isAnonymous: false,
    type: 'improvement_idea',
    content: 'We should include an exception clause in dowry guidelines for educational books, laptops, or vocational tools gifted to the bride by her own parents.',
    date: '1 day ago',
    upvotes: 38,
    status: 'approved'
  },
  {
    id: 'comm-2',
    surveyOrProposalId: 'surv-1',
    authorName: 'Anonymous Community Member',
    authorDistrict: 'Lucknow, UP East',
    isAnonymous: true,
    type: 'feedback',
    content: 'The feast guest limit of 250 is excellent, but we need strict local monitoring squads in tehsils so wealthy families do not bypass the rule privately.',
    date: '2 days ago',
    upvotes: 52,
    status: 'approved'
  },
  {
    id: 'comm-3',
    surveyOrProposalId: 'surv-1',
    authorName: 'Dr. Sadiya Khatoon',
    authorDistrict: 'Ahmedabad, Gujarat',
    isAnonymous: false,
    type: 'suggestion',
    content: 'Can we also mandate that at least 50% of the community scholarship fund goes to girls pursuing STEM and medical degrees? Highly needed!',
    date: '3 hours ago',
    upvotes: 14,
    status: 'pending_moderation'
  },
  {
    id: 'comm-4',
    surveyOrProposalId: 'surv-2',
    authorName: 'Haji Shabir Ahmad',
    authorDistrict: 'Indore, MP',
    isAnonymous: false,
    type: 'comment',
    content: 'Setting up IAS/IPS coaching institutes in Jaipur and Lucknow will transform the future of our youth within 5 years. Full support!',
    date: '2 days ago',
    upvotes: 61,
    status: 'approved'
  }
];

export const INITIAL_AI_ANALYTICS_DATA: Record<string, AIAnalyticsData> = {
  'default': {
    surveyId: 'surv-1',
    districtOpinion: [
      { district: 'Jaipur, Rajasthan', yesPct: 86, noPct: 9, neutralPct: 5, turnout: 88 },
      { district: 'Ahmedabad, Gujarat', yesPct: 91, noPct: 6, neutralPct: 3, turnout: 92 },
      { district: 'Lucknow, UP East', yesPct: 78, noPct: 15, neutralPct: 7, turnout: 74 },
      { district: 'Indore, MP', yesPct: 84, noPct: 11, neutralPct: 5, turnout: 81 },
      { district: 'Delhi NCR', yesPct: 89, noPct: 8, neutralPct: 3, turnout: 85 }
    ],
    ageGroupAnalysis: [
      { group: '18-25 Years (Youth)', percentage: 38, topConcern: 'Higher Education & Career Counseling' },
      { group: '26-45 Years (Mid-Career)', percentage: 42, topConcern: 'Zero-Dowry & Simple Marriage Norms' },
      { group: '46-60 Years (Elders)', percentage: 14, topConcern: 'Community Unity & Heritage Preservation' },
      { group: '60+ Years (Senior Citizens)', percentage: 6, topConcern: 'Pension Aid & Matrimonial Mediation' }
    ],
    educationTrends: [
      { educationLevel: 'Postgraduates & Professionals', participationRate: 94, supportRate: 92 },
      { educationLevel: 'University Graduates', participationRate: 88, supportRate: 86 },
      { educationLevel: 'Technical / Diploma Holders', participationRate: 82, supportRate: 84 },
      { educationLevel: 'Traditional Artisans / High School', participationRate: 75, supportRate: 81 }
    ],
    occupationTrends: [
      { occupation: 'Textile & Dyeing Artisans', participationRate: 89, supportRate: 88 },
      { occupation: 'Business Owners & Traders', participationRate: 85, supportRate: 82 },
      { occupation: 'Salaried Professionals / IT', participationRate: 91, supportRate: 93 },
      { occupation: 'Students & Research Scholars', participationRate: 95, supportRate: 96 }
    ],
    demographicParticipation: {
      womenParticipationPct: 44.8,
      youthParticipationPct: 38.2,
      seniorCitizenParticipationPct: 17.0
    },
    mostRequestedReforms: [
      { topic: 'Strict Dowry Abolition & Simple Marriage Charter', requestsCount: 4250, growthRate: '+34% YoY' },
      { topic: 'National IAS/IPS & Medical Scholarship Fund', requestsCount: 3890, growthRate: '+48% YoY' },
      { topic: 'Zero-Commission ONDC Textile Marketplace', requestsCount: 3120, growthRate: '+29% YoY' },
      { topic: 'District Sharia & Legal Reconciliation Cells', requestsCount: 2780, growthRate: '+22% YoY' },
      { topic: 'Tehsil Youth Anti-Addiction & Sports Grants', requestsCount: 2150, growthRate: '+41% YoY' }
    ],
    frequentlySuggestedTopics: [
      { tag: '#ZeroDowry', mentions: 1420, category: 'Marriage Norms' },
      { tag: '#YouthScholarships', mentions: 1280, category: 'Education' },
      { tag: '#HandblockEmpowerment', mentions: 980, category: 'Artisan Economy' },
      { tag: '#LegalAidCell', mentions: 850, category: 'Social Harmony' },
      { tag: '#DigitalEKyc', mentions: 760, category: 'E-Governance' },
      { tag: '#WomenEntrepreneurship', mentions: 690, category: 'Women Welfare' },
      { tag: '#SportsInfrastructure', mentions: 540, category: 'Youth Welfare' }
    ],
    heatMapsData: [
      { region: 'Western India (Rajasthan & Gujarat)', intensity: 'High', consensusScore: 89 },
      { region: 'Central India (Madhya Pradesh & Chhattisgarh)', intensity: 'High', consensusScore: 85 },
      { region: 'Northern India (UP West & Delhi NCR)', intensity: 'High', consensusScore: 87 },
      { region: 'Eastern India (UP East, Bihar & Jharkhand)', intensity: 'Medium', consensusScore: 78 },
      { region: 'Southern & Maharashtra Committees', intensity: 'Medium', consensusScore: 81 }
    ],
    trendAnalysis: {
      annualComparison: [
        { year: '2023', averageParticipation: 58, reformAdoptionRate: 64 },
        { year: '2024', averageParticipation: 69, reformAdoptionRate: 76 },
        { year: '2025', averageParticipation: 81, reformAdoptionRate: 85 },
        { year: '2026 (Current)', averageParticipation: 88, reformAdoptionRate: 91 }
      ],
      fiveYearComparison: [
        { metric: 'Digital Voter Participation %', val2022: '32.4%', val2024: '68.1%', val2026: '88.4%', trend: '+172% Surge' },
        { metric: 'Women’s Ballot Turnout %', val2022: '18.5%', val2024: '34.2%', val2026: '44.8%', trend: '+142% Growth' },
        { metric: 'National Reform Compliance %', val2022: '54.0%', val2024: '76.5%', val2026: '92.0%', trend: 'Exemplary' },
        { metric: 'Average Dispute Resolution Time', val2022: '8 Months', val2024: '3 Months', val2026: '14 Days', trend: 'Fast-Tracked' }
      ]
    }
  }
};

const createRes2025 = (
  id: string,
  no: string,
  titleEn: string, titleHi: string, titleUr: string,
  catEn: string, catHi: string, catUr: string,
  textEn: string, textHi: string, textUr: string,
  votes: number, approval: number, score: number,
  milestoneEn: string, milestoneHi: string, milestoneUr: string,
  gazette: string
): Resolution => ({
  id,
  resolutionNo: no,
  year: '2025',
  datePassed: '18 October 2025',
  effectiveDate: '1 November 2025',
  summitNameEn: '26th National All India Mahapanchayat Summit 2025',
  summitNameHi: '26वां अखिल भारतीय महापंचायत शिखर सम्मेलन 2025',
  summitNameUr: '26ویں قومی آل انڈیا مہاپنچایت سمٹ 2025',
  titleEn,
  titleHi,
  titleUr,
  categoryEn: catEn,
  categoryHi: catHi,
  categoryUr: catUr,
  officialTextEn: textEn,
  officialTextHi: textHi,
  officialTextUr: textUr,
  agendaEn: `Deliberation and enforcement of ${titleEn} across all registered committees.`,
  agendaHi: `${titleHi} पर विचार-विमर्श और सभी पंजीकृत समितियों में प्रवर्तन।`,
  agendaUr: `${titleUr} پر غور و فکر اور تمام رجسٹرڈ کمیٹیوں میں نفاذ۔`,
  totalVotes: votes,
  eligibleVoters: Math.round(votes * 1.11),
  participationRate: 90.2,
  approvalRate: approval,
  rejectionRate: +(100 - approval - 1.2).toFixed(1),
  abstainedRate: 1.2,
  committeeRecommendationEn: 'Unanimous Approval Recommended by National Sharia & Elder Council',
  committeeRecommendationHi: 'राष्ट्रीय शरिया और वरिष्ठ परिषद द्वारा सर्वसम्मति से अनुमोदन की सिफारिश',
  committeeRecommendationUr: 'قومی شریعہ اور بزرگ کونسل کی طرف سے متفقہ منظوری کی سفارش',
  finalDecisionEn: 'APPROVED & ENACTED BY MAHAPANCHAYAT 2025',
  finalDecisionHi: 'महापंचायत 2025 द्वारा स्वीकृत एवं लागू',
  finalDecisionUr: 'مہاپنچایت 2025 کے ذریعہ منظور اور نافذ',
  implementationCommitteeEn: 'National Sharia & District Enforcement Taskforce',
  implementationCommitteeHi: 'राष्ट्रीय शरिया एवं जिला प्रवर्तन कार्यबल',
  implementationCommitteeUr: 'نیشنل شریعہ اور ڈسٹرکٹ انفورسمنٹ ٹاسک فورس',
  progressStatusEn: `Active compliance verification across 350+ districts. Score: ${score}%`,
  progressStatusHi: `350+ जिलों में सक्रिय अनुपालन सत्यापन। स्कोर: ${score}%`,
  progressStatusUr: `350+ اضلاع میں فعال تعمیل کی تصدیق۔ اسکور: ${score}%`,
  implementationScore: score,
  status: 'implemented',
  keyMilestoneEn: milestoneEn,
  keyMilestoneHi: milestoneHi,
  keyMilestoneUr: milestoneUr,
  gazetteRef: gazette,
  supportingDocs: [
    { name: `${gazette}_Official_Gazette.pdf`, size: '3.1 MB', url: '#', type: 'pdf' }
  ],
  photos: [
    'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=600&auto=format&fit=crop&q=80'
  ],
  videos: [],
  pdfGazetteUrl: '#',
  meetingMinutesEn: `Passed with ${approval}% majority vote at the 2025 Mahapanchayat Summit.`,
  meetingMinutesHi: `2025 महापंचायत शिखर सम्मेलन में ${approval}% बहुमत से पारित।`,
  meetingMinutesUr: `2025 مہاپنچایت سمٹ میں ${approval}% اکثریت سے منظور।`,
  annualReviewEn: '2026 Audit: Nationwide compliance verified by district taskforces.',
  annualReviewHi: '2026 ऑडिट: जिला कार्यबलों द्वारा देशव्यापी अनुपालन सत्यापित।',
  annualReviewUr: '2026 آڈٹ: ضلعی ٹاسک فورسز کی طرف سے ملک گیر تعمیل کی تصدیق।',
  notifications: [
    'Published in Official Mahapanchayat Gazette on 1 November 2025.'
  ],
  historicalTimeline: [
    { year: '2025', date: '18 Oct 2025', eventEn: 'Approved at Mahapanchayat 2025 Summit', eventHi: 'महापंचायत 2025 शिखर सम्मेलन में स्वीकृत', eventUr: 'مہاپنچایت 2025 سمٹ میں منظور', status: 'Approved' },
    { year: '2025', date: '1 Nov 2025', eventEn: 'Enacted across all State Committees', eventHi: 'सभी राज्य समितियों में लागू', eventUr: 'تمام ریاستی کمیٹیوں میں نافذ', status: 'Active Implementation' }
  ]
});

export const INITIAL_RESOLUTIONS_DATA: Resolution[] = [
  {
    id: 'res-2026-1',
    resolutionNo: 'RES/2026/NAT-01',
    year: '2026',
    datePassed: '15 May 2026',
    effectiveDate: '1 June 2026',
    summitNameEn: '27th National All India Rangrez Mahapanchayat Summit (Jaipur)',
    summitNameHi: '27वां अखिल भारतीय रंगरेज महापंचायत शिखर सम्मेलन (जयपुर)',
    summitNameUr: '27ویں قومی آل انڈیا رنگریز مہاپنچایت سمٹ (جے پور)',
    titleEn: 'Universal Community Marriage Reform & Dowry Abolition Act',
    titleHi: 'सार्वभौमिक समाज विवाह सुधार एवं दहेज उन्मूलन अधिनियम',
    titleUr: 'یونیورسل کمیونٹی میرج ریفارم اور جہیز کے خاتمے کا ایکٹ',
    categoryEn: 'Social Reform & Matrimonial Bylaws',
    categoryHi: 'सामाजिक सुधार एवं वैवाहिक नियमावली',
    categoryUr: 'سماجی اصلاحات اور ازدواجی قوانین',
    officialTextEn: 'Complete ban on demanding dowry, cash gifts, or luxury vehicles. Wedding feasts are strictly capped at 250 guests per side with maximum 3 food items to prevent financial burden on families.',
    officialTextHi: 'दहेज, नकद उपहार या लक्जरी वाहनों की मांग पर पूर्ण प्रतिबंध। परिवारों पर वित्तीय बोझ को रोकने के लिए शादी के भोज को प्रति पक्ष 250 मेहमानों और अधिकतम 3 खाद्य पदार्थों तक सीमित किया गया है।',
    officialTextUr: 'جہیز، نقد تحائف یا لگژری گاڑیوں کے مطالبے پر مکمل پابندی۔ خاندانوں پر مالی بوجھ کو روکنے کے لیے شادی کی دعوتوں کو فی طرف 250 مہمانوں اور زیادہ سے زیادہ 3 کھانے کی اشیاء تک محدود کیا گیا ہے۔',
    agendaEn: 'Deliberation on eradicating lavish wedding expenditure and protecting middle-class families from debt trap.',
    agendaHi: 'भव्य शादी के खर्चों को खत्म करने और मध्यम वर्ग के परिवारों को कर्ज के जाल से बचाने पर विचार-विमर्श।',
    agendaUr: 'شادی کے شاہانہ اخراجات کو ختم کرنے اور متوسط طبقے کے خاندانوں کو قرض کے جال سے بچانے پر غور و فکر۔',
    
    totalVotes: 38450,
    eligibleVoters: 42100,
    participationRate: 91.3,
    approvalRate: 89.4,
    rejectionRate: 8.1,
    abstainedRate: 2.5,
    committeeRecommendationEn: 'Unanimous Approval Recommended by National Sharia & Elder Council',
    committeeRecommendationHi: 'राष्ट्रीय शरिया और वरिष्ठ परिषद द्वारा सर्वसम्मति से अनुमोदन की सिफारिश',
    committeeRecommendationUr: 'قومی شریعہ اور بزرگ کونسل کی طرف سے متفقہ منظوری کی سفارش',
    finalDecisionEn: 'APPROVED & ENACTED AS BINDING BYLAW',
    finalDecisionHi: 'स्वीकृत और अनिवार्य नियम के रूप में लागू',
    finalDecisionUr: 'منظور شدہ اور لازمی قانون کے طور پر نافذ',
    
    implementationCommitteeEn: 'National Matrimonial Compliance & District Qazi Taskforce',
    implementationCommitteeHi: 'राष्ट्रीय वैवाहिक अनुपालन एवं जिला काजी कार्यबल',
    implementationCommitteeUr: 'نیشنل میٹری مونیل کمپلائنس اور ڈسٹرکٹ قاضی ٹاسک فورس',
    progressStatusEn: 'Active Statewide Compliance Enforcement across 350+ Districts',
    progressStatusHi: '350+ जिलों में सक्रिय राज्यव्यापी अनुपालन लागू',
    progressStatusUr: '350+ اضلاع میں فعال ریاستی تعمیل کا نفاذ',
    implementationScore: 94,
    status: 'implemented',
    keyMilestoneEn: '94% reduction in reported dowry complaints & 12,000+ debt-free weddings conducted across Rajasthan, Gujarat, and MP.',
    keyMilestoneHi: 'दहेज शिकायतों में 94% की कमी और राजस्थान, गुजरात और एमपी में 12,000+ कर्ज मुक्त शादियां संपन्न।',
    keyMilestoneUr: 'جہیز کی شکایات میں 94 فیصد کمی اور راجستھان، گجرات اور ایم پی میں 12,000 سے زیادہ قرض کے بغیر شادیاں منعقد ہوئیں۔',
    gazetteRef: 'AIRA-GAZETTE-2026-DL-884',
    
    supportingDocs: [
      { name: 'Official_Dowry_Abolition_Gazette_2026.pdf', size: '4.2 MB', url: '#', type: 'pdf' },
      { name: 'District_Qazi_Enforcement_Guidelines.docx', size: '1.5 MB', url: '#', type: 'doc' }
    ],
    photos: [
      'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=600&auto=format&fit=crop&q=80'
    ],
    videos: ['https://www.youtube.com/embed/dQw4w9WgXcQ'],
    pdfGazetteUrl: '#',
    meetingMinutesEn: 'Summary: 418 district delegates participated. Motion tabled by Haji Rafiq Rangrez, seconded by Advocate Zainab Bibi. Passed with 89.4% majority vote.',
    meetingMinutesHi: 'सारांश: 418 जिला प्रतिनिधियों ने भाग लिया। हाजी रफीक रंगरेज द्वारा प्रस्ताव प्रस्तुत किया गया, एडवोकेट जैनब बीबी ने समर्थन किया। 89.4% बहुमत से पारित।',
    meetingMinutesUr: 'خلاصہ: 418 ضلعی مندوبین نے شرکت کی۔ حاجی رفیق رنگریز کی طرف سے پیش کردہ قرارداد، ایڈووکیٹ زینب بی بی کی تائید۔ 89.4 فیصد اکثریت سے منظور۔',
    annualReviewEn: '2026 Annual Audit: Compliance exceeds expectations. Recommended incentives for model districts.',
    annualReviewHi: '2026 वार्षिक ऑडिट: अनुपालन उम्मीदों से बेहतर। आदर्श जिलों के लिए प्रोत्साहन की सिफारिश की गई।',
    annualReviewUr: '2026 سالانہ آڈٹ: تعمیل توقعات سے بہتر۔ ماڈل اضلاع کے لیے مراعات کی سفارش کی گئی۔',
    notifications: [
      'Gazette Notification published in 14 state leading newspapers on 16 May 2026.',
      'Circular sent to all 350+ registered Sharia Nikah Registrars.'
    ],
    historicalTimeline: [
      { year: '2024', date: '12 Jan 2024', eventEn: 'Initial Draft Proposal submitted at Indore Conclave', eventHi: 'इंदौर सम्मेलन में प्रारंभिक मसौदा प्रस्ताव प्रस्तुत', eventUr: 'اندور کانکلیو میں ابتدائی ڈرافٹ تجویز پیش کی گئی', status: 'Draft Table' },
      { year: '2025', date: '20 Aug 2025', eventEn: 'District Convener Consultations & Pilot Testing in 15 Districts', eventHi: '15 जिलों में जिला संयोजक परामर्श और परीक्षण', eventUr: '15 اضلاع میں ڈسٹرکٹ کنوینر مشاورت اور پائلٹ ٹیسٹنگ', status: 'Committee Review' },
      { year: '2026', date: '15 May 2026', eventEn: 'Passed with 89.4% digital vote at Jaipur National Summit', eventHi: 'जयपुर राष्ट्रीय शिखर सम्मेलन में 89.4% डिजिटल वोट के साथ पारित', eventUr: 'جے پور قومی سمٹ میں 89.4% ڈیجیٹل ووٹ کے ساتھ منظور', status: 'Passed & Sealed' },
      { year: '2026', date: '1 June 2026', eventEn: 'Enforcement Act enacted across all 28 State Committees', eventHi: 'सभी 28 राज्य समितियों में प्रवर्तन अधिनियम लागू', eventUr: 'تمام 28 ریاستی کمیٹیوں میں نفاذ ایکٹ نافذ', status: 'Active Implementation' }
    ]
  },
  {
    id: 'res-2025-2',
    resolutionNo: 'RES/2025/NAT-04',
    year: '2025',
    datePassed: '18 October 2025',
    effectiveDate: '1 November 2025',
    summitNameEn: '26th National Educational & Youth Empowerment Conclave (Lucknow)',
    summitNameHi: '26वां राष्ट्रीय शिक्षा एवं युवा सशक्तिकरण सम्मेलन (लखनऊ)',
    summitNameUr: '26ویں قومی تعلیمی اور یوتھ ایمپاورمنٹ کانکلیو (لکھنؤ)',
    titleEn: 'Establishment of National Rangrez Higher Education & IAS/IPS Scholarship Fund',
    titleHi: 'राष्ट्रीय रंगरेज उच्च शिक्षा एवं IAS/IPS छात्रवृत्ति कोष की स्थापना',
    titleUr: 'قومی رنگریز اعلیٰ تعلیم اور IAS/IPS اسکالرشپ فنڈ کا قیام',
    categoryEn: 'Youth Empowerment & Education',
    categoryHi: 'युवा सशक्तिकरण एवं शिक्षा',
    categoryUr: 'نوجوانوں کو بااختیار بنانا اور تعلیم',
    officialTextEn: 'Every verified earning member shall contribute ₹100 monthly or ₹1,000 annually to fund 500 meritorious community students preparing for UPSC, state civil services, NEET, and JEE.',
    officialTextHi: 'UPSC, राज्य सिविल सेवा, NEET और JEE की तैयारी कर रहे 500 मेधावी समाज के छात्रों को वित्त पोषित करने के लिए प्रत्येक सत्यापित कमाने वाला सदस्य मासिक ₹100 या वार्षिक ₹1,000 का योगदान देगा।',
    officialTextUr: 'UPSC، ریاستی سول سروسز، NEET اور JEE کی تیاری کرنے والے 500 ہونہار برادری کے طلباء کو فنڈ فراہم کرنے کے لیے ہر تصدیق شدہ کمانے والا ممبر ماہانہ 100 روپے یا سالانہ 1000 روپے کا تعاونی فنڈ دے گا۔',
    agendaEn: 'Creating a dedicated corpus of ₹5 Crore annually for educational self-reliance and civil service representation.',
    agendaHi: 'शैक्षिक आत्मनिर्भरता और प्रशासनिक सेवा प्रतिनिधित्व के लिए प्रति वर्ष ₹5 करोड़ का समर्पित कोष बनाना।',
    agendaUr: 'تعلیمی خود انحصاری اور سول سروس کی نمائندگی کے لیے سالانہ 5 کروڑ روپے کا ایک مخصوص فنڈ بنانا۔',
    
    totalVotes: 35120,
    eligibleVoters: 39500,
    participationRate: 88.9,
    approvalRate: 94.2,
    rejectionRate: 4.8,
    abstainedRate: 1.0,
    committeeRecommendationEn: 'Highest Priority Endorsement by All India Educational Wing',
    committeeRecommendationHi: 'अखिल भारतीय शिक्षा विंग द्वारा सर्वोच्च प्राथमिकता समर्थन',
    committeeRecommendationUr: 'آل انڈیا ایجوکیشنل ونگ کی طرف سے اعلیٰ ترین ترجیحی توثیق',
    finalDecisionEn: 'APPROVED & CORPUS ACTIVATED',
    finalDecisionHi: 'स्वीकृत और कोष सक्रिय',
    finalDecisionUr: 'منظور شدہ اور فنڈ فعال',
    
    implementationCommitteeEn: 'National Scholarship Selection & Treasury Committee',
    implementationCommitteeHi: 'राष्ट्रीय छात्रवृत्ति चयन एवं कोष समिति',
    implementationCommitteeUr: 'نیشنل اسکالرشپ سلیکشن اور ٹریژری کمیٹی',
    progressStatusEn: 'Over 480 Meritorious Students Funded; 14 cleared UPSC prelims in 2026',
    progressStatusHi: '480 से अधिक मेधावी छात्र लाभान्वित; 2026 में 14 ने UPSC प्रारंभिक परीक्षा उत्तीर्ण की',
    progressStatusUr: '480 سے زیادہ ہونہار طلباء کو فنڈ فراہم کیا گیا؛ 2026 میں 14 نے UPSC پریلمز پاس کیا',
    implementationScore: 91,
    status: 'implemented',
    keyMilestoneEn: '₹4.6 Crore corpus collected; 480 scholars currently receiving direct bank DBT stipends.',
    keyMilestoneHi: '₹4.6 करोड़ का कोष एकत्र; 480 छात्र वर्तमान में सीधा बैंक DBT वजीफा प्राप्त कर रहे हैं।',
    keyMilestoneUr: '4.6 کروڑ روپے کا فنڈ جمع ہوا؛ 480 اسکالرز اس وقت براہ راست بینک ڈی بی ٹی وظیفہ وصول کر رہے ہیں۔',
    gazetteRef: 'AIRA-GAZETTE-2025-UP-419',
    
    supportingDocs: [
      { name: 'Scholarship_Fund_Bylaws_2025.pdf', size: '3.5 MB', url: '#', type: 'pdf' },
      { name: 'UPSC_Coaching_Partner_Institutes.xlsx', size: '890 KB', url: '#', type: 'doc' }
    ],
    photos: [
      'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&auto=format&fit=crop&q=80'
    ],
    videos: [],
    pdfGazetteUrl: '#',
    meetingMinutesEn: 'Unanimous applause at Lucknow conclave. Special audit panel appointed for transparent student selection.',
    meetingMinutesHi: 'लखनऊ सम्मेलन में सर्वसम्मत सराहना। पारदर्शी छात्र चयन के लिए विशेष ऑडिट पैनल नियुक्त किया गया।',
    meetingMinutesUr: 'لکھنؤ کانکلیو میں متفقہ تحسین۔ شفاف طالب علم کے انتخاب کے لیے خصوصی آڈٹ پینل مقرر کیا گیا۔',
    annualReviewEn: '2026 Mid-Year Review: 98% retention rate among selected scholars.',
    annualReviewHi: '2026 मध्य-वर्ष समीक्षा: चयनित छात्रों में 98% सफलता दर।',
    annualReviewUr: '2026 وسط سال کا جائزہ: منتخب اسکالرز میں 98% کامیابی کی شرح۔',
    notifications: [
      'Scholarship application portal opened online on 1 Nov 2025.',
      'DBT transfers initiated directly to students’ Aadhaar-linked accounts.'
    ],
    historicalTimeline: [
      { year: '2025', date: '10 Sep 2025', eventEn: 'Draft presented by Education Committee', eventHi: 'शिक्षा समिति द्वारा मसौदा प्रस्तुत', eventUr: 'ایجوکیشن کمیٹی کی جانب سے ڈرافٹ پیش', status: 'Tabled' },
      { year: '2025', date: '18 Oct 2025', eventEn: 'Passed with 94.2% majority in Lucknow Conclave', eventHi: 'लखनऊ सम्मेलन में 94.2% बहुमत से पारित', eventUr: 'لکھنؤ کانکلیو میں 94.2% اکثریت سے منظور', status: 'Passed' },
      { year: '2025', date: '1 Nov 2025', eventEn: 'National DBT Portal & Contribution Gateway launched', eventHi: 'राष्ट्रीय DBT पोर्टल और योगदान गेटवे शुरू किया गया', eventUr: 'نیشنل ڈی بی ٹی پورٹل اور کنٹریبیوشن گیٹ وے شروع کیا گیا', status: 'Active' }
    ]
  },
  createRes2025(
    'res-2025-01',
    'RES/2025/01',
    'Regular Meetings, Future Planning & Periodic Guidance Camps',
    'समाज के विकास एवं भविष्य निर्माण हेतु नियमित बैठकें व जागरूकता शिविर',
    'برادری کی ترقی اور مستقبل کی تعمیر کے لیے باقاعدہ اجلاس اور بیداری کیمپ',
    'Community Unity & Guidance',
    'सामुदायिक एकता एवं मार्गदर्शन',
    'برادری کا اتحاد اور رہنمائی',
    'To build a better future for the community through education, progressive thinking, employment opportunities, and dedication to the nation, regular meetings shall be organized from time to time. In addition, awareness programs and camps on de-addiction, healthcare, skill development, and small-scale industries shall be conducted regularly.',
    'शिक्षा, प्रगतिशील सोच, रोजगार के अवसरों और देश के प्रति समर्पण के माध्यम से समुदाय के लिए बेहतर भविष्य बनाने के लिए समय-समय पर नियमित बैठकें आयोजित की जाएंगी। इसके अलावा, नशा मुक्ति, स्वास्थ्य सेवा, कौशल विकास और लघु उद्योगों पर जागरूकता कार्यक्रम और शिविर नियमित रूप से आयोजित किए जाएंगे।',
    'تعلیم، روشن خیالی، روزگار کے مواقع اور وطن سے محبت کے ذریعے برادری کے بہتر مستقبل کے لیے وقتاً فوقتاً باقاعدہ اجلاس منعقد کیے جائیں گے۔ اس کے علاوہ، نشہ مکتی، صحت، مہارت کے فروغ، اور چھوٹی صنعتوں پر بیداری پروگرام اور کیمپ باقاعدگی سے منعقد کیے جائیں گے۔',
    38500, 96.8, 95,
    'Implemented — Regular guidance camps operational across 85% of districts.',
    'क्रियान्वित — 85% जिलों में नियमित मार्गदर्शन शिविर संचालित।',
    'نافذ العمل — 85 فیصد اضلاع میں باقاعدہ رہنمائی کیمپ جاری।',
    'AIRA-GAZETTE-2025-NAT-01'
  ),
  createRes2025(
    'res-2025-02',
    'RES/2025/02',
    'Simplicity in Marriage Ceremonies & Complete Ban on Band & DJ',
    'विवाह समारोहों में सादगी एवं बैंड, डीजे व आतिशबाजी पर पूर्ण प्रतिबंध',
    'شادی کی تقریبات میں سادگی اور بینڈ، ڈی جے و آتش بازی پر مکمل پابندی',
    'Austerity & Dignity in Marriages',
    'विवाहों में सादगी एवं गरिमा',
    'شادیوں میں سادگی اور وقار',
    'Marriage ceremonies shall be conducted with simplicity. The use of bands, DJs, fireworks, and similar extravagant practices has been completely prohibited by the unanimous decision of the community.',
    'विवाह समारोह सादगी के साथ संपन्न किए जाएंगे। समाज के सर्वसम्मति निर्णय द्वारा बैंड, डीजे, आतिशबाजी और इसी तरह की असाधारण और खर्चीली प्रथाओं के उपयोग को पूरी तरह से प्रतिबंधित कर दिया गया है।',
    'شادی کی تقریبات سادگی کے ساتھ منعقد کی جائیں گی۔ برادری کے متفقہ فیصلے کے تحت بینڈ، ڈی جے، آتش بازی اور اس طرح کے فضول اور مہنگے رواجوں کے استعمال پر مکمل طور پر پابندی عائد کر دی گئی ہے۔',
    37200, 91.8, 92,
    'Strictly Implemented — Approx. 92% Compliance Across District Committees.',
    'सख्ती से क्रियान्वित — जिला समितियों में लगभग 92% अनुपालन।',
    'سختی سے نافذ العمل — ضلعی کمیٹیوں میں تقریباً 92% پابندی۔',
    'AIRA-GAZETTE-2025-NAT-02'
  ),
  createRes2025(
    'res-2025-03',
    'RES/2025/03',
    'Nikah Timings Between Asr & Maghrib and Immediate Payment of Mehr in Cash',
    'असर और मगरिब के बीच निकाह का समय एवं नकद मेहर की तत्काल अदायगी',
    'عصر اور مغرب کے درمیان نکاح کا وقت اور نقد مہر کی فوری ادائیگی',
    'Shariah Compliance in Nikah',
    'निकाह में शरीयत अनुपालन',
    'نکاح میں شریعت کی پابندی',
    'Nikah (Islamic marriage) should be solemnized between the Asr and Maghrib prayers. If there is a genuine and unavoidable reason, it may be performed up to the Isha prayer. The amount of Mehr (dower) shall be fixed according to Islamic Shariah, and the Mehr must be paid immediately in cash at the time of Nikah.',
    'निकाह (इस्लामी विवाह) असर और मगरिब की नमाज के बीच संपन्न होना चाहिए। यदि कोई वास्तविक और अनिवार्य कारण है, तो इसे इशा की नमाज तक किया जा सकता है। मेहर की राशि इस्लामी शरीयत के अनुसार तय की जाएगी, और मेहर का भुगतान निकाह के समय नकद रूप में तुरंत किया जाना चाहिए।',
    'نکاح عصر اور مغرب کی نمازوں کے درمیان منعقد ہونا چاہیے۔ اگر کوئی معقول اور ناگزیر وجہ ہو تو اسے عشاء کی نماز تک کیا جا سکتا ہے۔ مہر کی رقم اسلامی شریعت کے مطابق طے کی جائے گی، اور مہر کی ادائیگی نکاح کے وقت نقد صورت میں فوری طور پر کی جانی چاہیے۔',
    36100, 92.4, 88,
    'Implemented — Approx. 88% Adherence in Community Weddings across states.',
    'क्रियान्वित — विभिन्न राज्यों में सामुदायिक विवाहों में लगभग 88% पालन।',
    'نافذ العمل — مختلف ریاستوں میں برادری کی شادیوں میں تقریباً 88% پابندی۔',
    'AIRA-GAZETTE-2025-NAT-03'
  ),
  createRes2025(
    'res-2025-04',
    'RES/2025/04',
    'Abolition of Customary Pre-Marriage Rituals (Lagun, Teeka, Portika)',
    'लगुन, टीका, पोर्तिका जैसी खर्चीली रस्मों की समाप्ति एवं केवल मंगनी की अनुमति',
    'لگن، ٹیکہ، پورتیکا جیسی فضول رسموں کا خاتمہ اور صرف منگنی کی اجازت',
    'Reform of Customs & Matrimonial Bylaws',
    'प्रथाओं में सुधार एवं वैवाहिक नियमावली',
    'رواجی اصلاحات اور ازدواجی قوانین',
    'The customs of Lagun (pre-marriage ceremony), Teeka, Portika (doorstep ritual), and similar traditions are hereby abolished. Instead, only an engagement (Mangni) ceremony may be held, during which any customary exchange may be completed. Thereafter, the marriage shall proceed directly with the Nikah ceremony.',
    'लगुन (विवाह पूर्व समारोह), टीका, पोर्तिका (द्वार रस्म) और इसी तरह की परंपराओं को एतद्द्वारा समाप्त किया जाता है। इसके स्थान पर केवल एक सगाई (मंगनी) समारोह आयोजित किया जा सकता है, जिसके दौरान कोई भी पारंपरिक आदान-प्रदान पूरा किया जा सकता है। इसके बाद, विवाह सीधे निकाह समारोह के साथ संपन्न होगा।',
    'لگن (شادی سے پہلے کی تقریب)، ٹیکہ، پورتیکا (دروازے کی رسم)، اور اس جیسی روایات کو اس کے ذریعے ختم کیا جاتا ہے۔ اس کے بجائے صرف ایک منگنی کی تقریب منعقد کی جا سکتی ہے، جس کے دوران کوئی بھی روایتی لین دین مکمل کیا جا سکتا ہے۔ اس کے بعد شادی براہ راست نکاح کی تقریب کے ساتھ منعقد ہوگی۔',
    35600, 90.8, 90,
    'Successfully Adopted — 90% Elimination of Unnecessary Pre-Marriage Rituals across district committees.',
    'सफलतापूर्वक स्वीकृत — जिला समितियों में अनावश्यक विवाह-पूर्व रस्मों में 90% की समाप्ति।',
    'کامیابی کے ساتھ مقبول — ضلعی کمیٹیوں میں غیر ضروری رسموں میں 90 فیصد کمی۔',
    'AIRA-GAZETTE-2025-NAT-04B'
  ),
  createRes2025(
    'res-2025-05',
    'RES/2025/05',
    'Fixed Honorarium of ₹2,100 for Qazi & ₹1,100 for Khidmat Services',
    'काजी साहब का हदिया ₹2,100 एवं खिदमत शुल्क ₹1,100 का निर्धारण',
    'قاضی صاحب کا ہدیہ 2,100 روپے اور خدمت فیس 1,100 روپے کا تعین',
    'Standardization of Religious Services',
    'धार्मिक सेवाओं का मानकीकरण',
    'مذہبی خدمات کو متفقہ بنانا',
    'For every Nikah, the honorarium for the Qazi shall be fixed at ₹2,100, and a service contribution of ₹1,100 shall be provided for Khidmat (Nikah-related services). This standardized honorarium ensures dignity, transparency, and uniformity across all community weddings.',
    'प्रत्येक निकाह के लिए, काजी साहब का हदिया (सम्मान राशि) ₹2,100 निर्धारित किया जाता है, और खिदमत (निकाह से संबंधित सेवाओं) के लिए ₹1,100 का सेवा योगदान प्रदान किया जाएगा। यह मानकीकृत सम्मान राशि सभी सामुदायिक विवाहों में गरिमा, पारदर्शिता और एकरूपता सुनिश्चित करती है।',
    'ہر نکاح کے لیے قاضی صاحب کا ہدیہ (اعزازیہ) 2,100 روپے مقرر کیا جاتا ہے، اور خدمت (نکاح سے متعلقہ خدمات) کے لیے 1,100 روپے کا تعاون فراہم کیا جائے گا۔ یہ متفقہ ہدیہ تمام برادری کی شادیوں میں وقار، شفافیت اور یکسانیت کو یقینی بناتا ہے۔',
    36800, 94.1, 92,
    'Standardized Rates Strictly Followed Across Local Jamaats and 350+ Sharia Registrars.',
    'स्थानीय जमातों और 350+ शरिया रजिस्ट्रारों में मानकीकृत दरों का सख्ती से पालन।',
    'مقامی جماعتوں اور 350+ شریعہ رجسٹراروں میں متفقہ نرخوں پر سختی سے عمل।',
    'AIRA-GAZETTE-2025-NAT-05'
  ),
  createRes2025(
    'res-2025-06',
    'RES/2025/06',
    'Prohibition of Printing Sacred Quranic Verses on Wedding Cards',
    'विवाह आमंत्रण कार्डों पर पवित्र कुरान की आयतों के मुद्रण पर पूर्ण प्रतिबंध',
    'شادی کے دعوتی کارڈوں پر مقدس قرآنی آیات کی چھپائی پر مکمل پابندی',
    'Sanctity of Sacred Texts',
    'पवित्र ग्रंथों की सम्मान व सुरक्षा',
    'مقدس تحریروں کا تقدس',
    'No verses of the Holy Quran or any sacred Islamic text shall be printed on wedding invitation cards. This binding rule prevents the accidental desecration or disrespect of holy texts when invitation cards are discarded after ceremonies.',
    'विवाह आमंत्रण कार्ड पर पवित्र कुरान की कोई भी आयत या कोई पवित्र इस्लामी पाठ मुद्रित नहीं किया जाएगा। यह नियम समारोहों के बाद निमंत्रण कार्ड फेंके जाने पर पवित्र ग्रंथों के आकस्मिक अनादर को रोकता है।',
    'شادی کے دعوتی کارڈ پر قرآن مجید کی کوئی آیت یا کوئی مقدس اسلامی متن نہیں چھاپا جائے گا۔ یہ لازمی اصول تقریبات کے بعد دعوتی کارڈ پھینکے جانے پر مقدس تحریروں کی بے ادبی کو روکتا ہے۔',
    38100, 96.5, 94,
    '94% Compliance Verified Across Community Printing Presses and District Jamaats.',
    'सामुदायिक प्रिंटिंग प्रेस और जिला जमातों में 94% अनुपालन सत्यापित।',
    'کمیونٹی پرنٹنگ پریس اور ضلعی جماعتوں میں 94 فیصد تعمیل کی تصدیق।',
    'AIRA-GAZETTE-2025-NAT-06'
  ),
  createRes2025(
    'res-2025-07',
    'RES/2025/07',
    'Community Welfare Fund via Marriage Contributions (₹2,100 & ₹1,100)',
    'विवाह अंशदान (₹2,100 एवं ₹1,100) से सामुदायिक कल्याण एवं शिक्षा कोष की स्थापना',
    'شادی کے عطیات (2,100 اور 1,100 روپے) سے برادری فلاحی اور تعلیمی فنڈ کا قیام',
    'Social Welfare & Education Corpus',
    'सामाजिक कल्याण एवं शिक्षा कोष',
    'سماجی بہبود اور تعلیمی فنڈ',
    'A Community Welfare Fund shall be established through mandatory marriage contributions. The groom’s family shall contribute ₹2,100 and the bride’s family shall contribute ₹1,100. The collected funds shall be utilized for the education of underprivileged children and supporting marriages of economically weaker youths.',
    'विवाह अंशदान के माध्यम से एक सामुदायिक कल्याण कोष स्थापित किया जाएगा। वर पक्ष का परिवार ₹2,100 का योगदान देगा और वधू पक्ष का परिवार ₹1,100 का योगदान देगा। एकत्रित धनराशि का उपयोग वंचित बच्चों की शिक्षा और आर्थिक रूप से कमजोर युवाओं के विवाह में सहायता के लिए किया जाएगा।',
    'شادی کے لازمی عطیات کے ذریعے ایک برادری فلاحی فنڈ قائم کیا جائے گا۔ دلہے کا خاندان 2,100 روپے اور دلہن کا خاندان 1,100 روپے کا تعاون کرے گا۔ جمع شدہ رقم کا استعمال مستحق بچوں کی تعلیم اور کمزور نوجوانوں کی شادیوں میں مدد کے لیے کیا جائے گا۔',
    35900, 91.4, 91,
    'Successfully Active — Welfare Fund Providing Regular Education & Marriage Aid across 91% of Units.',
    'सफलतापूर्वक सक्रिय — 91% इकाइयों में नियमित शिक्षा एवं विवाह सहायता प्रदान कर रहा कल्याण कोष।',
    'کامیابی کے ساتھ فعال — 91 فیصد یونٹوں میں باقاعدہ تعلیمی اور شادی کی امداد فراہم کرنے والا فلاحی فنڈ।',
    'AIRA-GAZETTE-2025-NAT-07'
  ),
  createRes2025(
    'res-2025-08',
    'RES/2025/08',
    'Simplicity in Funerals, No Graveyard Meals & Abolition of Teeja/Dasvi/Khach Feasts',
    'अंत्येष्टि में सादगी, कब्रिस्तान में भोजन घोषणा पर रोक एवं तीजा, दसवीं व चालीसवां दावत की समाप्ति',
    'تدفین میں سادگی، قبرستان میں کھانے کے اعلانات پر پابندی اور تیجا، دسویں و چالیسواں کی دعوت کا خاتمہ',
    'Funeral Austerity & Welfare',
    'अंत्येष्टि में सादगी एवं कल्याण',
    'تدفین میں سادگی اور فلاح',
    'During funeral and burial ceremonies, public announcements regarding meals at the graveyard shall be completely discontinued. Meals may only be arranged discreetly for immediate family members and close relatives who have travelled from a distance of 100 kilometers or more. Furthermore, the customs of Teeja (3rd day), Dasvi (10th day), Khach (40th day), and similar post-funeral feasts are hereby completely abolished.',
    'अंत्येष्टि और दफन समारोहों के दौरान, कब्रिस्तान में भोजन के संबंध में सार्वजनिक घोषणाएं पूरी तरह से बंद कर दी जाएंगी। भोजन केवल उन परिवार के सदस्यों और करीबी रिश्तेदारों के लिए गुप्त रूप से आयोजित किया जा सकता है जो 100 किलोमीटर या उससे अधिक की दूरी से यात्रा करके आए हैं। इसके अलावा, तीजा (तीसरा दिन), दसवीं (दसवां दिन), खाच (चालीसवां दिन) और इसी तरह के अंत्येष्टि के बाद के भोज को पूरी तरह से समाप्त किया जाता है।',
    'تدفین اور جنازے کی تقریبات کے دوران، قبرستان میں کھانے سے متعلق عوامی اعلانات مکمل طور پر بند کیے جائیں گے۔ کھانا صرف ان فوری خاندانی اراکین اور قریبی رشتہ داروں کے لیے خاموشی سے ترتیب دیا جا سکتا ہے جو 100 کلومیٹر یا اس سے زیادہ فاصلے سے سفر کر کے آئے ہیں۔ مزید برآں، تیجا (تیسرا دن)، دسویں، چالیسویں، اور اس جیسی تدفین کے بعد کی دعوتوں کو مکمل طور پر ختم کیا جاتا ہے۔',
    37500, 95.2, 93,
    'Implemented — 93% Adoption Across Rural & Urban Committees nationwide.',
    'क्रियान्वित — देश भर में ग्रामीण व शहरी समितियों में 93% स्वीकृति।',
    'نافذ العمل — ملک بھر میں دیہی اور شہری کمیٹیوں میں 93 فیصد مقبول।',
    'AIRA-GAZETTE-2025-NAT-08'
  ),
  createRes2025(
    'res-2025-09',
    'RES/2025/09',
    'Abolition of Ceremonial Offerings on Deceased (Dupatta/Lungi/Nemat) & Sadaqah Contribution',
    'मय्यत पर दुपट्टा, लुंगी या नेमत चढ़ाने की रस्म समाप्त एवं सदका (₹50/₹100) का प्रोत्साहन',
    'میت پر دوپٹہ، لنگی یا نعمت چڑھانے کی رسم کا خاتمہ اور صدقہ (50/100 روپے) کی ترغیب',
    'Charity & Funeral Austerity',
    'दान एवं अंत्येष्टि में सादगी',
    'خیرات اور تدفین میں سادگی',
    'The custom of placing Dupatta, Lungi (Nemat), or similar ceremonial offerings over the deceased is hereby abolished. Instead, individuals may contribute ₹50 or ₹100 as Sadaqah (charity) through the Imam of the local mosque or towards community welfare for the reward of the deceased.',
    'मृतक पर दुपट्टा, लुंगी (नेमत) या इसी तरह के पारंपरिक चढ़ावे चढ़ाने की प्रथा को एतद्द्वारा समाप्त किया जाता है। इसके स्थान पर, लोग मृतक के सवाब (पुण्य) के लिए स्थानीय मस्जिद के इमाम के माध्यम से या समाज कल्याण के लिए सदका (दान) के रूप में ₹50 या ₹100 का योगदान कर सकते हैं।',
    'میت پر دوپٹہ، لنگی (نعمت) یا اس جیسی رسمی اشیاء چڑھانے کی رسم کو اس کے ذریعے ختم کیا جاتا ہے۔ اس کے بجائے، لوگ میت کے ایصالِ ثواب کے لیے مقامی مسجد کے امام کے ذریعے یا برادری کی فلاح و بہبود کے لیے صدقہ (خیرات) کے طور پر 50 یا 100 روپے کا تعاون کر سکتے ہیں۔',
    36400, 91.5, 89,
    'Implemented — 89% Shift from Fabric Offerings to Cash Sadaqah across community mosques.',
    'क्रियान्वित — समुदाय की मस्जिदों में कपड़ा चढ़ावे से नकद सदका में 89% बदलाव।',
    'نافذ العمل — برادری کی مساجد میں کپڑا چڑھانے سے نقد صدقہ کی طرف 89 فیصد تبدیلی।',
    'AIRA-GAZETTE-2025-NAT-09'
  ),
  createRes2025(
    'res-2025-10',
    'RES/2025/10',
    'Simplicity & Minimum Expenditure in Marriages of Educated & Employed Women',
    'शिक्षित एवं कार्यरत युवतियों व महिलाओं के विवाह में सादगी एवं न्यूनतम खर्च',
    'تعلیم یافتہ اور برسرِ روزگار لڑکیوں اور خواتین کی شادیوں میں سادگی اور کم خرچ',
    'Women Empowerment & Austerity',
    'महिला सशक्तिकरण एवं सादगी',
    'خواتین کو بااختیار بنانا اور سادگی',
    'The marriages of educated girls and women who are employed should be conducted with simplicity and minimum expenditure.',
    'शिक्षित युवतियों और रोजगार करने वाली महिलाओं के विवाह सादगी और न्यूनतम व्यय के साथ संपन्न किए जाने चाहिए।',
    'تعلیم یافتہ لڑکیوں اور برسرِ روزگار خواتین کی شادیاں سادگی اور کم سے کم اخراجات کے ساتھ منعقد کی جانی چاہئیں۔',
    38200, 93.8, 86,
    'Successfully Active — 86% of Educated Youth Opting for Simple Weddings without dowry.',
    'सफलतापूर्वक सक्रिय — 86% शिक्षित युवा बिना दहेज के सादगीपूर्ण विवाह अपना रहे हैं।',
    'کامیابی کے ساتھ فعال — 86 فیصد تعلیم یافتہ نوجوان بغیر جہیز کے سادہ شادی کو ترجیح دے رہے ہیں۔',
    'AIRA-GAZETTE-2025-NAT-10'
  ),
  createRes2025(
    'res-2025-11',
    'RES/2025/11',
    'Registered Community Welfare Trust/NGO & ₹1,000 Household Contribution',
    'पंजीकृत समुदाय कल्याण ट्रस्ट/NGO की स्थापना एवं प्रति परिवार ₹1,000 वार्षिक योगदान',
    'رجسٹرڈ برادری فلاحی ٹرسٹ/این جی او کا قیام اور فی گھرانہ 1000 روپے کا تعاون',
    'Institutional Welfare & NGO',
    'संस्थागत कल्याण एवं NGO',
    'اداری فلاح اور این جی او',
    'A registered Community Welfare Trust/NGO shall be established for the welfare of poor, orphaned, and underprivileged children. Every household is encouraged to contribute ₹1,000 through online payment or community collection. The funds shall be utilized transparently for educational, social welfare, and other community development activities.',
    'गरीब, अनाथ और वंचित बच्चों के कल्याण के लिए एक पंजीकृत समुदाय कल्याण ट्रस्ट/एनजीओ स्थापित किया जाएगा। प्रत्येक परिवार को ऑनलाइन भुगतान या सामुदायिक संग्रह के माध्यम से ₹1,000 का योगदान करने के लिए प्रोत्साहित किया जाता है। धनराशि का उपयोग शैक्षिक, सामाजिक कल्याण और अन्य सामुदायिक विकास गतिविधियों के लिए पारदर्शी रूप से किया जाएगा।',
    'غریب، یتیم اور مستحق بچوں کی فلاح و بہبود کے لیے ایک رجسٹرڈ برادری فلاحی ٹرسٹ/این جی او قائم کیا جائے گا۔ ہر گھرانے کو آن لائن ادائیگی یا برادری کے جمع کرنے کے نظام کے ذریعے 1000 روپے کا تعاون کرنے کی ترغیب دی جاتی ہے۔ فنڈز کا استعمال تعلیمی، سماجی فلاح اور دیگر ترقیاتی کاموں کے لیے شفافیت کے ساتھ کیا جائے گا۔',
    37100, 92.1, 88,
    'Implemented — Trust Registered & Active Annual Contribution Collection in 88% of Areas.',
    'क्रियान्वित — ट्रस्ट पंजीकृत एवं 88% क्षेत्रों में सक्रिय वार्षिक अंशदान संग्रह।',
    'نافذ العمل — ٹرسٹ رجسٹرڈ اور 88 فیصد علاقوں میں فعال سالانہ تعاون جمع بندی।',
    'AIRA-GAZETTE-2025-NAT-11'
  ),
  createRes2025(
    'res-2025-12',
    'RES/2025/12',
    'Discontinuation of Post-Barat Khodiya, Drama & Entertainment Gatherings',
    'बारात रवानगी के बाद महिलाओं के खोड़िया, नाटक व मनोरंजन कार्यक्रमों पर रोक',
    'بارات کی روانگی کے بعد خواتین کے کھوڑیہ، ناٹک اور تفریحی پروگراموں پر پابندی',
    'Moral Decorum & Marriages',
    'नैतिक शालीनता एवं विवाह',
    'اخلاقی شائستگی اور شادیاں',
    'The practice of organizing Khodiya, drama, theatrical performances, or similar entertainment programs for women after the departure of the wedding procession (Barat) is hereby discontinued.',
    'विवाह बारात रवानगी के बाद महिलाओं के लिए खोड़िया, नाटक, नाटकीय प्रदर्शन या इसी तरह के मनोरंजन कार्यक्रमों को आयोजित करने की प्रथा को एतद्द्वारा समाप्त किया जाता है।',
    'شادی کی بارات روانہ ہونے کے بعد خواتین کے لیے کھوڑیہ، ناٹک، تھیٹر کے مظاہرے، یا اس جیسے تفریحی پروگراموں کا انعقاد کرنے کی رسم کو اس کے ذریعے ختم کیا جاتا ہے۔',
    39400, 94.2, 91,
    'Implemented — 91% Discontinuation Across Towns and Villages.',
    'क्रियान्वित — कस्बों और गांवों में 91% समाप्ति।',
    'نافذ العمل — قصبوں اور دیہاتوں میں 91 فیصد خاتمہ।',
    'AIRA-GAZETTE-2025-NAT-12'
  ),
  createRes2025(
    'res-2025-13',
    'RES/2025/13',
    'No Separate Home Biryani Feasts in Conference Marriages & Simple Walima',
    'सामूहिक (कॉन्फ्रेंस) विवाहों में घर पर अलग बिरयानी दावत नहीं व वलीमा ऐच्छिक',
    'اجتماعی (کانفرنس) شادیوں میں گھر پر الگ بریانی دعوت نہیں اور ولیمہ اختیاری',
    'Conference Marriages & Austerity',
    'सामूहिक विवाह एवं सादगी',
    'اجتماعی شادیاں اور سادگی',
    'In community or conference marriages, no separate Biryani feast or meal shall be organized at home. The groom’s family may arrange a simple Walima meal according to their wishes and financial capacity; however, it shall not be considered compulsory.',
    'सामूहिक या कॉन्फ्रेंस विवाहों में, घर पर अलग से कोई बिरयानी दावत या भोजन आयोजित नहीं किया जाएगा। वर पक्ष का परिवार अपनी इच्छा और वित्तीय क्षमता के अनुसार एक साधारण वलीमा भोजन की व्यवस्था कर सकता है; हालाँकि, इसे अनिवार्य नहीं माना जाएगा।',
    'برادری یا کانفرنس کی اجتماعی شادیوں میں، گھر پر الگ سے کوئی بریانی دعوت یا کھانا منعقد نہیں کیا جائے گا۔ دلہے کا خاندان اپنی خواہش اور مالی گنجائش کے مطابق ایک سادہ ولیمہ ترتیب دے سکتا ہے؛ تاہم، اسے لازمی نہیں سمجھا جائے گا۔',
    41200, 95.6, 95,
    'Successfully Active — 95% Compliance in Collective Marriage Events.',
    'सफलतापूर्वक सक्रिय — सामूहिक विवाह आयोजनों में 95% अनुपालन।',
    'کامیابی کے ساتھ فعال — اجتماعی شادیوں میں 95 فیصد تعمیل।',
    'AIRA-GAZETTE-2025-NAT-13'
  ),
  createRes2025(
    'res-2025-14',
    'RES/2025/14',
    'Multi-Level Monitoring Committees at District, Tehsil, Block, Town & Village Levels',
    'संकल्पों के क्रियान्वयन हेतु जिला, तहसील, ब्लॉक, नगर व ग्राम स्तर पर समितियां',
    'قراردادوں کے نفاذ کے لیے ضلعی، تحصیل، بلاک، قصبہ اور گاؤں کی سطح پر کمیٹیاں',
    'Grassroots Oversight & Governance',
    'जमीनी निगरानी एवं प्रशासन',
    'نچلی سطح پر نگرانی اور نظم و نسق',
    'Committees shall be constituted at the district, tehsil, block, town, and village levels to oversee the implementation of these social reform resolutions. These committees shall promote awareness, guide community members, and ensure the effective implementation of the resolutions wherever necessary.',
    'इन समाज सुधार प्रस्तावों के क्रियान्वयन की निगरानी के लिए जिला, तहसील, ब्लॉक, नगर और ग्राम स्तर पर समितियों का गठन किया जाएगा। ये समितियां जागरूकता को बढ़ावा देंगी, समाज के सदस्यों का मार्गदर्शन करेंगी और जहाँ भी आवश्यक हो संकल्पों का प्रभावी क्रियान्वयन सुनिश्चित करेंगी।',
    'ان سماجی اصلاحاتی قراردادوں کے نفاذ کی نگرانی کے لیے ضلعی، تحصیل، بلاک، قصبہ، اور گاؤں کی سطح پر کمیٹیاں تشکیل دی جائیں گی۔ یہ کمیٹیاں بیداری کو فروغ دیں گی، برادری کے اراکین کی رہنمائی کریں گی، اور جہاں بھی ضرورت ہو قراردادوں کے موثر نفاذ کو یقینی بنائیں گی۔',
    43500, 97.1, 96,
    'Implemented — 1,200+ Active Committees Functioning Nationwide.',
    'क्रियान्वित — देश भर में 1,200+ सक्रिय समितियां कार्यरत।',
    'نافذ العمل — ملک بھر میں 1,200 سے زیادہ فعال کمیٹیاں سرگرمِ عمل।',
    'AIRA-GAZETTE-2025-NAT-14'
  )
];
